<section class="cookie">
    <header class="cookie-header">
        <h1 class="head-title cookie-title">Polityka plików cookie</h1>
    </header>
    <div class="cookie-text">
        <p class="p-text">Nasza strona internetowa wykorzystuje pliki cookie.</p>
        <p class="p-text">Korzystamy z cookie sesyjnego w celu podniesienia bezpieczeństwa mechanizmu wysyłania wiadomości poprzez formularz kontaktowy na stronie <a href="/kontakt">kontaktu z naszą firmą</a>.</p>
        <p class="p-text">Zapisujemy też na Twoim komputerze cookie stałe, które przez okres 2 lat pamięta że zapoznałeś się z tą informacją.</p>
        <p class="p-text">Możesz skonfigurować tak swoją przeglądarkę aby nie akceptowała plików cookie. Uniemożliwi to jednak wysłanie wiadmości poprzez formularz kontaktowy.</p>
        <p class="p-text">Jeśli zdecydujesz się nie akceptować plików cookie, wówczas w celu wysłania wiadomości skorzystaj z aplikacji poczty elektronicznej i wyślij wiadomość na adres: <a href="mailto:biuro@sadzonka.eu">biuro@sadzonka.eu</a></p>

        <h3 class="aside-title cookie-subtitle">Czym są pliki cookie:</h3>

        <p class="s-text">Cookie to pliki tekstowe umieszczane na komputerze użytkownika w celu identyfikcji tego urządzenia.</p> 
        <p class="s-text">Pliki cokie zapewniają większy komfort przeglądania stron internetowych.</p>

        <h3 class="aside-title cookie-subtitle">Jak zablokować pliki cookie?</h3>

        <p class="s-text">Zapoznaj się jak ustawić lub zablokować pliki cookie w Twojej przeglądarce:</p>
        
        <ul class="cookie-list">
            <li class="cookie-list-item"><a href="http://support.microsoft.com/kb/196955/pl" target="_blank" class="cookie-list-link">Internet Explorer</a></li>
            <li class="cookie-list-item"><a href="http://support.mozilla.org/pl/kb/ciasteczka" target="_blank" class="cookie-list-link">Firefox</a></li>
            <li class="cookie-list-item"><a href="http://support.google.com/chrome/bin/answer.py?hl=pl&amp;answer=95647" target="_blank" class="cookie-list-link">Chrome</a></li>
        </ul>

        <h3 class="aside-title cookie-subtitle">Więcej informacji o plikach cookie:</h3>

        <ul class="cookie-list">
            <li class="cookie-list-item"><a href="http://pl.wikipedia.org/wiki/HTTP_cookie" target="_blank" class="cookie-list-link">Wikipedia</a>
            <li class="cookie-list-item"><a href="http://www.giodo.gov.pl/169/id_art/1026/j/pl/" target="_blank" class="cookie-list-link">GIODO</a>     
            <li class="cookie-list-item"><a href="http://www.aboutcookies.org/" target="_blank" class="cookie-list-link">About Cookies </a>
        </ul>
    </div>
</section>