<section>

    <div class="review-text">
        <p class="p-text">zawartość strony: </p>
        <ul>
            <li><a href="#prace">Remont: opis prac, rzuty, galeria zdjęć domu</li>
            <li><a href="#opis">Stan istniejący: rzuty, opis budynku</li>
        </ul>

        <div  class="prace">
            <a name="prace"/>
           <h4 class="head-title">Remont/przebudowa:</h4>
           <h6 class="aside-title">Rzuty (przewidywany stan po remoncie):</h6>
           
            <ul>
                        <li><a href="/rzut"> parter</a></li>  
                        <li><a href="/rzut,k,poddasze">poddasze</a></li>
                        <li><a href="/rzut,k,przekroj-wschod">przekrój wschodni</a></li>
                        <li><a href="/rzut,k,front-poludnie">front południowy</a></li>
                        <!-- -->  
                        <li><a href="/rzut,k,przekroj-zachod">przekrój zachodni</a></li>
                        <li><a href="/rzut,k,front-polnoc">front północnego</a>
                        </li>
                    </ul>
           
           <p class="p-text">Powierzchnia po remoncie: <?php echo (5.8 + 1.8 + 5 + 9 + 10.5 + 16.85 + 18.96 + 8.5 + 3.5); ?></p>
           <br/><br/>
           <h6 class="aside-title">Prace do wykonania:</h6>
            <ul>
                <li>WYBURZENIA<br><br>
                    - Rozbiórka ściany szczytowej zachodniej<br>
                    -Rozbiórka północnego ganku blaszanego<br>
                    -Rozbiórka pomieszczenia gospodarczego ~24m2,  pozostałyby tylko fundamenty, <br>
                    -Rozbiórka kominów, <br>  
                    -Wyburzenie otworu drzwiowego 230x90cm w ścianie wschodniej parteru, będzie to wyjście z pokoju do holu, <br>
                    -Pogłębienie w dół otworów okiennych na balkonowe(2 lub 3 jeśli nie ma przeciwskazań), połączenie dwóch okien północnych w jedno okno - szczegóły w przygotowaniu</li>

                </li>   
                <li>PRZEBUDOWA POMIESZCZENIA GOSPODARCZEGO NA HAL<br>    
                    Na pozostałym po stodole podniesionym fundamencie  budowa: hal(~310x280) i balkon/minitaras (~350x120) =  480x350<br><br>
                    Ściany pustach porotherm, sufit powieszany, daszek spadek pomiędzy 280cm a 210cm wysokości parteru w halu, <br>
                    daszek dwuspadowy na osi północ-południe,
                    <br /><br />
                    szczegóły na rysunkach w przygotowaniu

                </li> 

                <li>  Wzmocnie stropów Klein'a:
                    <br>  <br>
                    Wzmocnienie samych teowników od dołu, od góry: usunięcie  podłogi, resztek starego wypełnienia, wysypanie kuleczek keramzytowych, <br>
                    nowe legary co 50cm + podłoga  legary będą gęściej niż jest to obecnie (podłoga się ugina, legary są co 1m wzdłuż teowników położone)  - lepsza byłaby wylewka jeśli jest taka możliwość ??<br>
                </li>
                <li>Wzmocnienie stropu żelbetowego o powierzchni 3.5m2</li>
                <li> Nowy(lub wzmocniony) strop drewniany nad parterem  i nowa więźba dachowa, pokrycie dachowe blacha trapezowa 'aluminiowa':
                    <br><br>
                <li>Nowy kąt nachylenia dachu 35stopni, wysokość strychu zamiast obecnej 428cm będzie 330cm, dach czterospadowy zamiast dachu dwuspadowego (jesli to możliwe? ekonomicznie/urzędowo)<br>
                </li>
                <li> Ocieplenie i izolacja przeciwwilgociowa murów domu  wraz z fundamentami piwnic i posadzką (obecnie brak ocieplenia poziomego piwnic i izolacji przeciwwilgociowej )</li>
                <li>prace na strychu: okna połaciowe 2x 60x80  na stronie południowej, ocieplenie stropu nad parterem, ofasowania kominów, dobudowa nowych wywietrzników<br>
                </li>                
            </ul> 
<br/><br/>
            <h4 class="aside-title">Galeria zdjęć:</h4>   

            <p class="p-text">W  <a href="/galeria">galerii </a> zdjęcia więźby dachowej , fragmenty stropu Kleina, <?php /*fragmenty fundamentów od strony zewnętrznej oraz*/?> pogłądowy rysunek ewentualnie nowego kształtu dachu.</p>

            
        </div>

        <div  class="opis">
      <a name="opis"/>      
            
            <h4 class="head-title">Stan istniejący:</h4>
            <h6 class="aside-title">Rzuty (wstęp do inwentryzacji):</h6> 
            <ul>
                <li><a href="/rzut,k,parter-inwent">parter </a></li>
                <li><a href="/rzut,k,poddasze-inwent">poddasze </a></li> 
                <li><a href="/rzut,k,piwnica">piwnice </a></li> 

                <li><a href="/rzut,k,przekroj-wschod-inwent">przekroj wschodni </a></li> 
                <li><a href="/rzut,k,przekroj-zachod-inwent">przekroj zachodni </a></li> 

                <li><a href="/rzut,k,front-polnoc-luk-inwent">front północny </a></li> 
                <li><a href="/rzut,k,front-poludnie-inwent">front południowy </a></li>

            </ul>
<br/><br/>
            <h6 class="aside-title">Opis budynku:</h6>
            <p class="p-text">
                Jest to budynek parterowy podpiwniczony wybudowany w latach około 1958 - 1960,   z piwnicami tylko pod częścią mieszkalną. Do części mieszkalnej przylega pomieszczenie gospodarcze , 
                <br>które kiedyś było stodołą.</p>

            <ul>
                <li>Piwnice wystają z gruntu na około od 60 do 160cm, </li>
                <li>wysokość piwnic: 210cm, </li>
                <li>wysokość parteru 280cm, </li>
                <li>poddasze bez ścianki kolankowej, </li>
                <li>kąt nachylenia dachu około 42 stopnie,</li>
                <li>wysokość ścian szczytowych to około 4,28cm.</li>
                <li> Ściany szczytowe domu są na osi wschód-zachód.</li>
                <li> fundamenty to układany kamień na zaprawie cementowej po zewnętrznej części a w środku mieszany pustak(betonowy?) + cegla - nie znam ich głębokości</li> 
            </ul>

            <p class="p-text">

                <br>
                Dom posiada mury zewnętrzne dwuwarstwowe, warstwa zewnętrzna cegła pełna, wewnątrz mieszana cegła pełna,pustak zużlowy/haszowy, ubijany hasz, grubość całości 42cm.
            </p>

            <p class="p-text">

                Piwnice posiadają mury z pustaka betonowego(częściowo cegły) oraz 2 rodzaje stropów nad piwnicami:</p>

            <ul>
                <li>nad 2 pokojami strop Kleina:<br>
                    - wymiary 420x405 - 3 teowniki długości 410cm  ,<br>
                    - wymiary 420x456 - 3 teowniki długości 456cm, <br>
                    - rozstaw 100cm <br>
                    - szerokość teownika 11 cm, wysokość nieznana, grubość około 4-5mm(??), przestrzeń pomiędzy teownikami wypełniona jest cegłą i otynkowana. <br>
                    - Nad tymi stropami znajduje się podłoga na legarach, <br>
                    - materiał wypełniający to zaprawa wapienno piaskowa<br>
                    - Jedna piwnica do około 1975 r. była stajnią ,  tutaj teownik jest najbardziej skorodowany<br>
                    - druga od około 10lat miała ocieplony od strony piwnicy strop styropianem grubości około 2-3cm. po usuunięciu ocieplenia teownik okazał się mniej skorodowany w porównaniu do  drugiej piwnicy
                </li> 
                <li>Teowniki są skorodowane (nie znam grubości skorodowania). </li>
                <li>     
                    Reszta stropów jest żelbetowa, pod łazienką jest mocno zniszczony</li>

            </ul>

            <p class="p-text">
                Pomieszczenie gospodarcze kiedyś było stodołą o wymiarach  320x840cm, to pomieszczenie podzielone jest fundamentem na dwie części.<br>

                w 1. części wysokość 345 x 420 x 320cm  + wysokosć  ścian szczytowych 4.28m <br>
                w 2 część: wysokość 280 x 420 x 320cm  + wysokosć  ścian szczytowych 4.28m <br>

                to pomioeszczenie ma otwartą przestrzenią do  ściany szczytowej, brak okna, są tylko drzwi wejściowe szer 90cm x210cm, <br>
                ściana północna kiedyś była drewnianą bramą wejściową, obecnie ten fragment zamurowany jest jednowarstwowym pustakiem haszowym z pozostawionym otworem na drzwi jw. <br>
                Ściany tego pomieszczenia wykonane są z mieszanego materiału są jednowarstwowe z pustaka, pełnej cegły i ubijanego haszu. <br>
                W połowie pomieszczenia wykonany jest fundament wysokości około  ~ 60-80cm ponad grunt.
            </p> 
        </div>

</section>

<?php $this->ob(); ?>
<script src="/js/mig/mig.switcher.dom.js"></script>
<script type="text/javascript">
    // <![CDATA[
    // 
    // 
    //var canv = jQuery('#canvas');

    //console.log(canv);
    //
    mig.switcher.dom(window, {
    });
    // ]]>
</script>
<?php $this->clean(); ?>