<div class="main error404">
    <?php if ($this->code == 404): ?>
        <div class="p-text error404-description">Strona o podanym adresie  nie istnieje.</div>
    <?php else: ?>
        <div class="p-text error503-description">Strona chwilowo niedostępna. Prosimy spróbować ponownie.</div>
    <?php endif; ?>
    <div class="review-photo-1 img-fluid"></div>
    <div class="review-photo-2 img-fluid"></div>
    <div class="review-photo-3 img-fluid"></div>
</div>