<div class="header-domain-img">
    <h1>RRZEBUDOWA DOMU </h1>
    
    <!--
                                             
                   stodoły z dobudową małego holu na tym miejscu                          
                       http://www.mercor.com.pl/page,pro,id,3519,farby_peczniejace___konstrukcje_stalowe.html                      
                                             
                                             
                                             http://www.panewnik.com.pl/pdf/plyta_wps.pdf   https://pl.wikipedia.org/wiki/Strop_WPS http://metalkom.com.pl/?page_id=109   na cele mieszkaniowe oraz rozbiórki pomieszczenia gospodarczego --></h1>
</div>
