<section>
    <?php $this->render('projection/view/partial/tools.phtml'); ?> 
    <svg  version="1.1"
          baseProfile="full"
          accesskey=""
          class="svg-canvas"
          viewBox="0 0 968 945"
          width="968" 
          height="945">
   <?php $this->render('projection/view/partial/style.phtml'); ?>

    <rect  x="0" y="0" width="968" height="945" fill="#ccc" stroke="black"/>
    <rect  x="42" y="42" width="884" height="861" fill="#fff" stroke="black"/>

    <!-- strop -->

    <rect  x="250" y="42" width="350" height="420" fill="#fffccc" stroke="black"/>

    <!-- schody -->
    <rect  x="42" y="42" width="85" height="420" fill="#fffccc" stroke="black"/>
    <rect  x="128" y="372" width="112" height="90" fill="#fffccc" stroke="black"/>
    
    <rect  x="128" y="42" width="10" height="330" fill="#ccc" stroke="black"/>
<rect  x="128" y="360" width="120" height="10" fill="#ccc" stroke="black"/>
    <!-- sciany nosne -->

    <rect  x="42" y="462" width="884" height="28" fill="#ccc" stroke="black"/> <!-- nosna -->
    <rect  x="446" y="489" width="28" height="416" fill="#ccc" stroke="black"/><!-- nosna ?  salon -->

    <!-- kominy -->
    <rect  y="490" x="475" width="16" height="22" fill="#ccc" stroke="black"/>


    <!-- sciany dzialowe -->
    <rect  y="42" x="240" width="12" height="420" fill="#ccc" stroke="black"/><!-- dzialowa sien -->  

    <rect  y="42" x="446" width="12" height="261" fill="#ccc" stroke="black"/><!-- dzialowa spizarka -->

    <rect  y="42" x="604" width="12" height="420" fill="#ccc" stroke="black"/><!-- dzialowa lazienka -->

   

    <rect  y="303" x="252" width="352" height="12" fill="#ccc" stroke="black"/><!-- dzialowa przedpokoj -->

    <!-- okna -->
    <rect  x="127" y="0" width="96" height="42" fill="#ffccff" stroke="black"/><!-- okno sien -->
    <rect  x="348" y="0" width="55" height="42" fill="#ffccff" stroke="black"/><!-- okno spizarka -->

    <rect  x="471" y="0" width="55" height="42" fill="#ffccff" stroke="black"/><!-- okno lazienka -->
    <!--<rect  x="680" y="0" width="160" height="42" fill="red" stroke="black"/>-->
    <rect  x="699" y="0" width="122" height="42" fill="#ffccff" stroke="black"/><!-- okno kuchnia -->

    
    <rect  x="178" y="903" width="165" height="42" fill="#ffccff" stroke="black"/><!-- okno salon -->

    <rect  x="639" y="903" width="165" height="42" fill="#ffccff" stroke="black"/><!-- okno sypialnia -->
    

  <rect  x="680" y="462" width="160" height="28" fill="red" stroke="black"/>
    
  

    <rect stroke="black" fill="red" height="140" width="12" x="600" y="320"/>
    <rect stroke="black" fill="#333" height="12" width="60" x="617" y="303"/>
    <rect stroke="black" fill="#333" height="12" width="60" x="865" y="303"/>



    <!-- drzwi -->
    <rect  x="128" y="48" width="10" height="90" fill="#ffcccc" stroke="black"/>
    <rect  x="240" y="368" width="12" height="90" fill="#ffcccc" stroke="black"/><!-- drzwi sien -->
    <rect  x="333.5" y="303" width="85" height="12" fill="#ffcccc" stroke="black"/><!-- drzwi spizarka -->
    <rect  x="460.5" y="303" width="85" height="12" fill="#ffcccc" stroke="black"/><!-- drzwi lazienka -->
    <rect  x="604" y="364" width="12" height="96" fill="#ffcccc" stroke="black"/><!-- drzwi kuchnia -->

    <rect  x="280" y="462" width="88" height="28" fill="#ffcccc" stroke="black"/><!-- drzwi salon -->
    <rect  x="500" y="462" width="90" height="28" fill="#ffcccc" stroke="black"/><!-- drzwi sypialnia -->

    <!-- nowe drzwi -->
    <rect  x="926" y="619" width="42" height="90" fill="red" stroke="black"/><!-- okno sypialnia -->



 <!-- <rect  x="926" y="365" width="42" height="90" fill="red" stroke="black"/>-->

    <!-- teksty -->


    <!-- tekst sien -->    
    <text x="140" y="30">w:96</text>
    <text x="50" y="230">w:90/85</text>
    <text x="60" y="80">sień/+klatka schodowa</text>
    <text x="60" y="120">198x420=8.32</text>


    <!-- tekst spizarka --> 
    <text x="355" y="30">w:55</text>
    <text x="280" y="80">spiżarka/łazienka</text>
    <text x="280" y="120">194x261=5.06</text>

    <!-- tekst łazienka --> 
    <text x="475" y="30">w:55</text>
    <text x="470" y="80">łazienka/gos.CO</text>
    <text x="470" y="120">146x261=3.81</text>


    <!-- tekst kuchnia --> 
    <text x="735" y="35">w:122</text>
    <text x="670" y="20">w:160/150 x140wys</text>
    <text x="670" y="80">kuchnia</text>
    <text x="670" y="120">310x420=13.02</text>

    <!-- tekst przedpokój --> 
    <text x="280" y="360">przedpokój</text>
    <text x="280" y="390">156x353=5.51</text>

    <!-- tekst salon --> 
    <text x="225" y="930">w:162</text>
    <text x="190" y="850">sypialnia</text>
    <text x="190" y="880">405x416=16.85</text>
    <text x="300" y="482">w:88</text>

    <!-- tekst sypialnia -->
    <text x="925" y="680">w:90</text>
    
    <text x="685" y="940">w:162</text>
    <text x="650" y="850">sypialnia</text>
    <text x="650" y="880">456x416=18.96</text>    
    <text x="525" y="482">w:90</text>

  

    <g class="wywierzniki">
    <rect stroke="black" fill="yellow" height="40" width="40" x="560" y="260"/>
    <text x="570" y="290">CO</text> 

    <rect stroke="black" fill="yellow" height="15" width="15" x="458" y="42"/>
    <text x="475" y="60">WC</text> 
    </g>
    </svg>     
</section>

<?php $this->ob(); ?>
<script src="/js/mig/mig.canvas.view.js"></script>
<script type="text/javascript">
    // <![CDATA[
   
    mig.canvas.view(window, {});
    // ]]>
</script>
<?php $this->clean(); ?>
    