<section> 
    <?php $this->render('projection/view/partial/tools.phtml'); ?>
    
     
   <svg  version="1.1"
         baseProfile="full"
         accesskey=""
        class="svg-canvas"
         viewBox="0 0 1320 945"
         width="1320" 
         height="945">
<?php $this->render('projection/view/partial/style.phtml'); ?>
  
  <rect  x="0" y="0" width="1320" height="945" fill="#ccc" stroke="black"/>
  <rect  x="42" y="42" width="1236" height="861" fill="#fff" stroke="black"/>
  
    <!-- strop -->
  <rect  y="42" x="42" width="926" height="861" fill="#fffccc" stroke="black"/><!-- dzialowa kuchnia -->
 <!-- <rect  x="42" y="42" width="1236" height="162" fill="transparent" stroke="black"/>-->
   <line x1="42" y1="92" x2="1278" y2="92" stroke-width="2" stroke="red"/> 
  <line x1="42" y1="240" x2="1278" y2="240" stroke-width="2" stroke="orange"/>    
  
   <line x1="42" y1="853" x2="1278" y2="853" stroke-width="2" stroke="red"/> 
  <line x1="42" y1="705" x2="1278" y2="705" stroke-width="2" stroke="orange"/> 
  
  <!-- kominy -->
  <rect  y="490" x="475" width="16" height="22" fill="#ccc" stroke="black"/>
  
  <rect  y="400" x="950" width="40" height="40" fill="#ccc" stroke="black"/>  
  
  <rect stroke="black" fill="#ffccff" height="50" width="42" x="0" y="447.5"/> 
    
    <text x="1150" y="88" fill="red">skos < ~120</text>
    <text x="1150" y="870" fill="red">skos < ~120</text>
    
    <text x="1150" y="228" fill="orange">skos < ~210</text>
    <text x="1150" y="725" fill="orange">skos < ~210</text>
    
    <text x="10" y="472">~1m x 60cm</text> 
     <text x="50" y="72">strop drewniany</text>
     <text x="940" y="420">komin</text> 
    <text x="475" y="480">komin</text> 
     <g class="wywierzniki">
        <rect stroke="black" fill="yellow" height="40" width="40" x="560" y="260"/>
        <text x="570" y="290">CO</text> 

        <rect stroke="black" fill="yellow" height="15" width="15" x="458" y="42"/>
        <text x="475" y="60">WC</text> 
    </g>
</svg>     
</section>

<?php $this->ob(); ?>
<script src="/js/mig/mig.canvas.view.js"></script>
    <script type="text/javascript">
    // <![CDATA[
    // 
    // 
        //var canv = jQuery('#canvas');
   
   //console.log(canv);
   //
   mig.canvas.view(window, {
            
        });
    // ]]>
    </script>
    <?php $this->clean(); ?>
    