<span class="p-text contact-text-label">E-mail: </span><span itemprop="email" class="p-text contact-text">Zenobia i Ewa Batko,  <br/>adres: Pawlikowice 113, dz. nr 451<br/> 32-020 Wieliczka<br/><a href="mailto:ewa.k.batko@gmail.com">ewa.k.batko@gmail.com</a></span><br>
<span class="p-text contact-text-label">Telefon: </span><span itemprop="telephone" class="p-text contact-text"><b>504 867 151</b></span><br> 49.966012, 20.055593                    
<?php /*<span class="p-text contact-text-label">Adres inwestycji: </span><br>
<span itemprop="streetAddress" class="p-text contact-text">xxx</span><br>
<span itemprop="postalCode" class="p-text contact-text">32-020</span>  -, 12 651 51 61
<span itemprop="addressLocality" class="p-text contact-text">Wieliczka</span>
<br>
<span class="p-text contact-text-label">Adres Siedziby: </span><br>
<span itemprop="streetAddress" class="p-text contact-text">xxx</span><br>
<span itemprop="postalCode" class="p-text contact-text">32-020</span>  -
<span itemprop="addressLocality" class="p-text contact-text">Wieliczka</span>
<br>
<span itemprop="addressRegion" class="p-text contact-text">Małopolska</span>
<span itemprop="addressCountry" class="p-text contact-text">Polska.</span>
 * */
?>