<section> 
    <?php $this->render('projection/view/partial/tools.phtml'); ?>
    <!--<div class="list-switcher">
      <a href="#" class="switcher" data-id-to-switch="lukarna">pokaż lukarna</a>
    </div>-->
   <svg  version="1.1"
         baseProfile="full"
         accesskey=""
        class="svg-canvas"
         viewBox="0 0 1320 958"
         width="1320" 
         height="958">
<?php $this->render('projection/view/partial/style.phtml'); ?>
  
  <rect  x="0" y="0" width="1320" height="958" fill="#ccc" stroke="black"  />
  
  <rect  x="0" y="0" width="1320" height="428" fill="#99ccff" stroke="black"/> 
 
   <rect  x="394" y="748" width="888" height="210" fill="#fff" stroke="black"/> 
   
   <rect  x="42" y="748" width="310" height="210" fill="brown" stroke="black"/>
   
   
   <rect  x="42" y="448" width="1236" height="280" fill="#fff" stroke="black"/>
   
     <!-- piwnica okna -->
    
    <rect  x="525" y="760" width="42" height="51" fill="#ffccff" stroke="black"/>
    <rect  x="1124" y="760" width="95" height="65" fill="#ffccff" stroke="black"/>
   
    
    
   
   
    
   
   <polygon points="348,428 836.5,98 1325,428" fill="#fff" stroke="black" />
   
   
   
    
    <!-- sciani parter <line x1="352" y1="448" x2="352" y2="728" stroke-width="1" stroke="black"/>-->
    <g class="scianki"> 
   
      
    
    <line x1="638" y1="448" x2="638" y2="728" stroke-width="1" stroke="black"/>
    <line x1="648" y1="448" x2="648" y2="728" stroke-width="1" stroke="black"/>
    
    <line x1="972" y1="448" x2="972" y2="728" stroke-width="1" stroke="black"/>
    <line x1="977" y1="448" x2="977" y2="728" stroke-width="1" stroke="black"/>
 
    
    
    <line x1="704" y1="748" x2="704" y2="958" stroke-width="1" stroke="black"/>
    <line x1="716" y1="748" x2="716" y2="958" stroke-width="1" stroke="black"/>
    </g>
    
   <rect  x="352" y="448" width="42" height="280" fill="#ccc"  stroke="black"/> 
    
    <rect  x="1097" y="488" width="66" height="160" fill="#ffccff"  stroke="black"/>
     
     
    
   <rect  x="185" y="528" width="95" height="200" fill="#ffccff"  stroke="black"/>
   <rect  x="180" y="728" width="105" height="100" fill="grey"  stroke="black"/>
    
    <!-- grunt  -->
   <polygon points="0,815 0,958 1320,958 1320,860" fill="brown" stroke="black"/>
    
   
   
       <rect  x="500" y="488" width="122" height="160" fill="#fff" stroke="black"/> 
    <rect  x="500" y="488" width="90" height="230" fill="#ffccff" stroke="black"/>
<rect  x="500" y="648" width="90" height="70" fill="red" stroke="black"/>
   
    
    <rect  x="795" y="488" width="160" height="160" fill="#ffccff" stroke="black"/>
    
     <rect  x="850" y="488" width="68" height="160" fill="red" stroke="black"/>
    <!-- kominy -->
   
   <rect  x="808" y="90" width="30" height="50" fill="#666" stroke="black"/>
   <rect  x="1188" y="305" width="30" height="50" fill="#666" stroke="black"/>
   <rect  x="968" y="155" width="30" height="50" fill="#666" stroke="black"/>
    
  <text x="875" y="816">kąt: <?php echo round(rad2deg(atan(105/185)));?>, h:105,w:185</text>
    
  
  <rect x="1" y="428" width="350" height="70" fill="#fff" stroke="black"></rect>
    
   <!-- 
   sien sciana i schody
   
   <rect  x="1187" y="448" width="90" height="280" fill="#fffccc" stroke="black"/>
    
    <rect  x="1068" y="448" width="12" height="280" fill="#ccc" stroke="black"/>-->
    
    <!-- tekst piwnica --> 
    <text x="179" y="493">daszek</text>
   <text x="180" y="593">h:200,w:95</text> 
    <text x="199" y="523">hol</text>
    <text x="199" y="753">schody</text>
    
    <text x="1082" y="593">h:160,w:66</text>
    
    <text x="482" y="593">h:230,w:90</text>
    <text x="782" y="563">h:160(155),w:160</text>
    
    
    
    <text x="720" y="770">piwnica, h:210</text>
    
    <text x="500" y="810">w:42, h:51</text>
    <text x="1082" y="810">w:95, h:65</text>
    
     <!-- tekst parter -->    
    <text x="580" y="470">parter, h:280</text>
    
     <!-- tekst poddasze -->    
   
    
 
     
     
     
          <text x="680" y="400">h:330 strych</text>

     <!--        lukarna wersja 2             -->
     
     
     
     
     
   <!-- <text x="845" y="300">h:210x90x2</text>
    <text x="130" y="140">daszek lukarna,h:~70</text>-->
    
     <!-- tekst strych -->      
     
      <text x="425" y="445">h:~20 strop drewniany</text>
      <text x="425" y="745">h:~20 strop żelbetowy</text>
   
    
</svg>     
</section>

<?php $this->ob(); ?>
<script src="/js/mig/mig.canvas.view.js"></script>
    <script type="text/javascript">
    // <![CDATA[
    // 
    // 
        //var canv = jQuery('#canvas');
   
   //console.log(canv);
   //
   mig.canvas.view(window, {
            
        });
    // ]]>
    </script>
    <?php $this->clean(); ?>
    