<section> 
    <?php $this->render('projection/view/partial/tools.phtml'); ?>
    <!--<div class="list-switcher">
     <a href="#" class="switcher" data-id-to-switch="lukarna-zachod">pokaż lukarna zachod</a>
     <a href="#" class="switcher" data-id-to-switch="lukarna-srodkowa">pokaż lukarna srodkowa</a>
     <a href="#" class="switcher" data-id-to-switch="lukarna-wschod">pokaż lukarna wschod</a>
    </div>-->
   <svg  version="1.1"
         baseProfile="full"
         accesskey=""
        class="svg-canvas"
         viewBox="0 0 968 958"
         width="968" 
         height="958">
   
<?php $this->render('projection/view/partial/style.phtml'); ?>
  
  <rect  x="0" y="0" width="968" height="958" fill="#ccc" stroke="black"/>
  
  <rect  x="0" y="0" width="968" height="428" fill="#99ccff" stroke="black"/> 
 
   <rect  x="42" y="748" width="888" height="210" fill="#fff" stroke="black"/> 
  
  
   <rect  x="42" y="448" width="968" height="280" fill="#fff" stroke="black"/>
   
     <!-- piwnica okna -->
    
    
    <rect  x="199" y="780" width="100" height="71" fill="#ffccff" stroke="black"/>
   
   <rect  x="643" y="780" width="102" height="71" fill="#ffccff" stroke="black"/>
     
   
   <!-- okna strych -->
   <rect  x="580" y="30" width="50" height="50" fill="#ffccff" stroke="black"/>
   <rect  x="810" y="30" width="50" height="50" fill="#ffccff" stroke="black"/>
   
 <!--     <g class="lukarna-srodkowa"> 
     <rect  x="570" y="178" width="298" height="20" fill="#ccc"  stroke="black"/>
    <rect  x="570" y="198" width="298" height="20" fill="#ccc"  stroke="black"/>
    
   <rect  x="570" y="218" width="39" height="210" fill="#ccc"  stroke="black"/>
   <rect  x="609" y="218" width="90" height="210" fill="red"  stroke="black"/>
   <rect  x="699" y="218" width="39" height="210" fill="#ccc" stroke="black"/>
   <rect  x="738" y="218" width="90" height="210" fill="red"  stroke="black"/>
   <rect  x="828" y="218" width="39" height="210" fill="#ccc"  stroke="black"/>
   </g>
   
   <g class="lukarna-wschod">
  <rect  x="1045" y="178" width="168" height="20" fill="#ccc"  stroke="black"/>
    <rect  x="1045" y="198" width="168" height="20" fill="#ccc"  stroke="black"/>
   <rect  x="1045" y="218" width="39" height="210" fill="#ccc"  stroke="black"/>   
   <rect  x="1084" y="218" width="90" height="210" fill="red"  stroke="black"/>
   <rect  x="1174" y="218" width="39" height="210" fill="#ccc"  stroke="black"/>
   </g>
   
   <g class="lukarna-zachod">
   <rect  x="174" y="178" width="168" height="20" fill="#ccc"  stroke="black"/>
    <rect  x="174" y="198" width="168" height="20" fill="#ccc"  stroke="black"/>
   <rect  x="174" y="218" width="39" height="210" fill="#ccc"  stroke="black"/>   
   <rect  x="213" y="218" width="90" height="210" fill="red"  stroke="black"/>
   <rect  x="303" y="218" width="39" height="210" fill="#ccc"  stroke="black"/>
   </g>-->
   
  <g class="lukarna-zachod">  
   <rect  x="213" y="218" width="90" height="140" fill="red"  stroke="black"/>
   </g>
  <g class="lukarna-srodkowa">
   <rect  x="609" y="218" width="90" height="140" fill="red"  stroke="black"/>
    <rect  x="738" y="218" width="90" height="140" fill="red"  stroke="black"/>
    </g>  
   <!-- kominy -->
   
   <rect  x="931" y="0" width="30" height="50" fill="#666" stroke="black"/>
   <rect  x="475" y="0" width="30" height="50" fill="#666" stroke="black"/>
   

   <!-- scianki poddasze -->
    <rect  x="0" y="0" width="42" height="428" fill="#99ccff" stroke="black"/>
  
   <rect  x="0" y="128" width="1320" height="20" fill="#99ccff" stroke="black"/>
   
   <rect  x="450" y="148" width="20" height="280" fill="#99ccff" stroke="black"/>
   

    <!-- scianki -->
    
    <line x1="447" y1="448" x2="447" y2="728" stroke-width="1" stroke="black"/>
    <line x1="475" y1="448" x2="475" y2="728" stroke-width="1" stroke="black"/>
    
  <!--  <line x1="447" y1="748" x2="447" y2="958" stroke-width="1" stroke="black"/>
    <line x1="475" y1="748" x2="475" y2="958" stroke-width="1" stroke="black"/>
 
    
    <line x1="931" y1="448" x2="931" y2="728" stroke-width="1" stroke="black"/>
    <line x1="973" y1="448" x2="973" y2="728" stroke-width="1" stroke="black"/>-->
     
     <!--okna parter -->
     
    <rect  x="178" y="488" width="165" height="160" fill="#ffccff" stroke="black"/>
    
    
    <rect  x="639" y="488" width="162" height="160" fill="#ffccff" stroke="black"/> 
     

 
    
     
     
    
    
    <rect  x="639" y="488" width="162" height="160" fill="transparent" stroke="black"/>
    
    
    
    <!-- grunt 
   <polygon points="0,908 0,958 1320,958 1320,863" fill="brown" stroke="black"/> -->
  
   <polygon points="0,908 0,958 972,958 972,863" fill="brown" stroke="black"></polygon>
   
  
    
    
   
    
    <!-- teksty zachod--> 
    <text x="135" y="303">h:160,w:90 okno połaciowe</text>
    <text x="185" y="593">h:162,w:160</text>
   <text x="185" y="833">h:71,w:100</text>
    
     <!-- tekst srodek -->    
   
    <text x="640" y="300">h:160x90x2 okna połaciowe</text>    
   <text x="640" y="593">h:160x160</text>
    <text x="640" y="833">h:71,w:102</text>
   
   <!-- tekst wschod --> 
   <text x="1082" y="393">h:210,w:90</text>
 <text x="1032" y="593">h:230x90 + 160x90</text>    
  
 
 
    <text x="60" y="30">h:128 strych</text>
     <text x="60" y="340">h:280 poddasze</text>
     <text x="60" y="680">h:280 parter</text>
     <text x="60" y="880">h:210 piwnica</text>
         
     <!-- tekst stropy -->      
      <text x="455" y="145">h:~20 strop drewniany</text>
      <text x="425" y="445">h:~20 strop drewniany</text>
      <text x="425" y="745">h:~20 strop Kleina</text>
   
    
</svg>     
</section>

<?php $this->ob(); ?>
<script src="/js/mig/mig.canvas.view.js"></script>
    <script type="text/javascript">
    // <![CDATA[
    // 
    // 
        //var canv = jQuery('#canvas');
   
   //console.log(canv);
   //
   mig.canvas.view(window, {
            
        });
    // ]]>
    </script>
    <?php $this->clean(); ?>
    