<section>
    <?php $this->render('projection/view/partial/tools.phtml'); ?> 
    <svg  version="1.1"
          baseProfile="full"
          accesskey=""
          class="svg-canvas"
          viewBox="0 0 1320 945"
          width="1320" 
          height="945">
          <?php $this->render('projection/view/partial/style.phtml'); ?>

    <rect  x="0" y="0" width="1320" height="945" fill="#ccc" stroke="black"/>
    <rect  x="42" y="42" width="1236" height="861" fill="#fff" stroke="black"/>

    <rect  x="968" y="0" width="350" height="462" fill="orange" stroke="black" style="opacity: 0.5"/>

    <!-- schody -->
    <rect  x="42" y="142" width="112" height="198" fill="#fffccc" stroke="black"/>
    
    
    
    
    <rect  x="150" y="142" width="10" height="320" fill="#ccc" stroke="black"/>
    <rect  x="42" y="142" width="118" height="10" fill="#ccc" stroke="black"/>
    <rect  x="968" y="462" width="350" height="42" fill="#ccc" stroke="black"/>
    <rect  x="968" y="782" width="350" height="42" fill="#ccc" stroke="black"/>
<rect  x="970" y="826" width="350" height="120" fill="grey" stroke="black"/>
    <rect  x="160" y="240" width="80" height="8" fill="#ccc" stroke="black"/>

    <!-- sciany nosne -->

    <rect  x="42" y="462" width="884" height="28" fill="#ccc" stroke="black"/> <!-- nosna -->
    <rect  x="446" y="489" width="28" height="416" fill="#ccc" stroke="black"/><!-- nosna ?  salon -->

    <!-- kominy -->
    <rect  y="490" x="475" width="16" height="22" fill="#ccc" stroke="black"/>


    <g id="meble-kuchnia">
    <rect  y="42" x="340" width="330" height="60" fill="white" stroke="black"/>
    <rect  y="102" x="608" width="60" height="240" fill="white" stroke="black"/>
    <rect  y="192" x="390" width="60" height="140" fill="white" stroke="black"/>
    <rect  y="232" x="390" width="60" height="60" fill="white" stroke="black"/>


    </g>

    <g id="meble-sypialnia-mala">
    <rect  y="250" x="805"  width="100" height="210" fill="white" stroke="black"/>
    <rect  y="250" x="908"  width="15" height="210" fill="white" stroke="black"/>
    <rect y="44" x="862"  width="60" height="200" fill="white" stroke="black"/>
    <rect  y="240" x="685" width="40" height="80" fill="white" stroke="black"/>
    <rect  y="130" x="685" width="80" height="60" fill="white" stroke="black"/>     
    </g>

    <g id="meble-sypialnia-duza">
    <rect  y="490" x="46" width="60" height="120" fill="white" stroke="black"/>
    <rect  y="520" x="130" width="60" height="50" fill="white" stroke="black"/>

    <rect  y="615" x="70" width="240" height="50" fill="white" stroke="black"/>
    <rect  y="665" x="120" width="145" height="165" fill="white" stroke="black"/>
    <rect  y="650" x="385" width="60" height="240" fill="white" stroke="black"/> 
    <rect  y="550" x="395" width="50" height="80" fill="white" stroke="black"/>
    </g>




    <rect id="dywan-salon" y="620" x="539" width="300" height="200" fill="white" stroke="black"/>
    <g id="meble-salon">
    <rect y="494" x="605"  width="160" height="40" fill="white" stroke="black"/>
    <rect  y="760" x="477" width="47" height="130" fill="white" stroke="black"/>

    <rect y="690" x="838"  width="85" height="195" fill="white" stroke="black"/>
    <rect  y="530" x="863" width="60" height="60" fill="white" stroke="black"/>

    <rect  y="670" x="560" width="215" height="87" fill="white" stroke="black"/>
    <rect  y="670" x="560" width="165" height="87" fill="white" stroke="black"/>

    <rect  y="600" x="630" width="45" height="50" fill="white" stroke="black"/>
    <rect  y="600" x="720" width="45" height="50" fill="white" stroke="black"/>
    <rect  y="600" x="580" width="45" height="50" fill="white" stroke="black"/>

    <rect  y="680" x="500" width="45" height="50" fill="white" stroke="black"/>
    <rect  y="680" x="785" width="45" height="50" fill="white" stroke="black"/>

    <rect  y="790" x="720" width="45" height="50" fill="white" stroke="black"/>
    <rect  y="790" x="630" width="45" height="50" fill="white" stroke="black"/>
    <rect  y="790" x="580" width="45" height="50" fill="white" stroke="black"/>
    <rect  y="564" x="475" width="60" height="90" fill="white" stroke="black"/>
    </g>

    <g id="meble-hol">
    <rect  y="679" x="1225" width="50" height="100" fill="white" stroke="black"/>
    <rect  y="505" x="1150" width="120" height="60" fill="white" stroke="black"/>

    <rect  y="620" x="1130" width="60" height="60" fill="white" stroke="black"/>
    <rect  y="702" x="985" width="60" height="60" fill="white" stroke="black"/>

    <rect  y="628" x="1050" width="50" height="50" fill="white" stroke="black"/>

    </g>

    <g id="meble-taras">
    <rect  y="845" x="1125" width="50" height="50" fill="white" stroke="black"/>

    <rect  y="845" x="1195" width="60" height="60" fill="white" stroke="black"/>
    <rect  y="845" x="990" width="60" height="60" fill="white" stroke="black"/>

    </g>


    <g id="lazienka">
    <rect  y="42" x="42" width="90" height="100" fill="#81DAF5" stroke="black"/>
    <rect  y="192" x="162" width="65" height="40" fill="#81DAF5" stroke="black"/>
    <rect  y="252" x="165" width="40" height="65" fill="#81DAF5" stroke="black"/>
    <rect  y="42" x="405" width="80" height="60" fill="#81DAF5" stroke="black"/>
    <rect  y="292" x="225" width="20" height="40" fill="#81DAF5" stroke="black"/>

    <polygon class="wanna" points="252,42 338,42 338,192 308,192" fill="#81DAF5" stroke="black"/>
    </g>
    <rect  y="220" x="340" width="40" height="60" fill="#81DAF5" stroke="black"/>






    <!-- sciany dzialowe -->
    <rect  y="192" x="380" width="8" height="150" fill="#ccc" stroke="black"/><!-- dzialowa sien -->  
    <rect  y="192" x="338" width="50" height="8" fill="#ccc" stroke="black"/>
    <rect  y="42" x="338" width="8" height="150" fill="#ccc" stroke="black"/>




    <rect  y="240" x="240" width="8" height="220" fill="#ccc" stroke="black"/><!-- dzialowa spizarka -->

    <rect  y="42" x="670" width="12" height="420" fill="#ccc" stroke="black"/><!-- dzialowa lazienka -->

    <rect  y="42" x="926" width="42" height="861" fill="#ccc" stroke="black"/><!-- dzialowa kuchnia -->

    <rect  y="333" x="248" width="140" height="8" fill="#ccc" stroke="black"/><!-- dzialowa przedpokoj -->

    <!-- okna -->
    <rect  x="127" y="0" width="96" height="42" fill="#ffccff" stroke="black"/><!-- okno sien -->
    <rect  x="127" y="0" width="30" height="42" fill="#f5f5f5" stroke="black"/>

    <rect  x="348" y="0" width="55" height="42" fill="#ffccff" stroke="black"/><!-- okno spizarka -->

    <rect  x="471" y="0" width="55" height="42" fill="#ffccff" stroke="black"/><!-- okno lazienka -->
    <rect  x="401" y="0" width="68" height="42" fill="red" stroke="black"/>
    <rect  x="699" y="0" width="122" height="42" fill="#ffccff" stroke="black"/><!-- okno kuchnia -->
    <rect  x="699" y="0" width="32" height="42" fill="#f5f5f5" stroke="black"/>
    <rect  x="350" y="0" width="25" height="42" fill="#f5f5f5" stroke="black"/>
    <rect  x="526" y="0" width="10" height="42" fill="red" stroke="black"/>
    <rect  x="1035" y="462" width="95" height="42" fill="orange" stroke="black"/><!-- drzwi stodola -->
    <rect  x="1030" y="270" width="105" height="190" fill="orange" stroke="black"/>
    <rect  x="1065" y="782" width="128" height="42" fill="orange" stroke="black"/>

<rect x="530" y="360" width="90" height="90" fill="#fffccc" stroke="black"></rect>


    <rect  x="178" y="903" width="165" height="42" fill="#ffccff" stroke="black"/><!-- okno salon -->

    <rect  x="639" y="903" width="165" height="42" fill="#ffccff" stroke="black"/><!-- okno sypialnia -->



    <!-- drzwi -->
    <rect  x="150" y="368" width="10" height="90" fill="#ffcccc" stroke="black"/><!-- drzwi sien -->
    <rect  x="240" y="368" width="8" height="90" fill="#ffcccc" stroke="black"/><!-- drzwi sien -->
    <!-- <rect  x="333.5" y="303" width="85" height="12" fill="#ffcccc" stroke="black"/>drzwi spizarka -->
    <rect  x="260" y="333" width="80" height="8" fill="#ffcccc" stroke="black"/><!-- drzwi lazienka -->
    <rect  x="670" y="350" width="12" height="80" fill="#ffcccc" stroke="black"/><!-- drzwi kuchnia -->

    <rect  x="280" y="462" width="88" height="28" fill="#ffcccc" stroke="black"/><!-- drzwi salon -->
    <rect  x="500" y="462" width="90" height="28" fill="#ffcccc" stroke="black"/><!-- drzwi sypialnia -->

    <rect  x="926" y="595" width="42" height="90" fill="red" stroke="black"/><!-- drzwi sypialnia --> 



    <g id="grzejniki">
    <rect id="grzejnik-salon" y="496" x="790" width="130" height="15" fill="violet" stroke="black"/>
    <rect id="grzejnik-hal" y="513" x="975" width="15" height="60" fill="violet" stroke="black"/>
    <rect id="grzejnik-sypialnia-mala" y="445" x="705" width="90" height="15" fill="violet" stroke="black"/>
    <rect id="grzejnik-sypialnia-duza" y="496" x="175" width="90" height="15" fill="violet" stroke="black"/>
    <rect id="grzejnik-przedpokoj" y="448" x="390" width="90" height="15" fill="violet" stroke="black"/>

    <rect id="grzejnik-wc" y="254" x="225" width="15" height="30" fill="violet" stroke="black"/>

    <rect id="grzejnik-lazienka" y="245" x="255" width="15" height="80" fill="violet" stroke="black"/>
    <rect id="grzejnik-kuchnia" y="125" x="350" width="15" height="60" fill="violet" stroke="black"/>
    </g>

    <g id="instalacja-co">
    <polygon points="246,258 362,258"  stroke="violet" stroke-width="4"/>   
    <polygon points="362,188 362,462"  stroke="violet" stroke-width="4"/>   
    <polygon points="477,493  990,494"  stroke="violet" stroke-width="4"/>
    <polygon points="265,493 448,492"  stroke="violet" stroke-width="4"/>
    </g>

    <g id="instalacja-h20-zimna">
    <polygon points="110,43 602,43"  stroke="#58D3F7" stroke-width="4"/>
    <polygon points="348,43 348,488"  stroke="#58D3F7" stroke-width="4"/>
    <polygon points="165,252 350,252"  stroke="#58D3F7" stroke-width="4"/>
    <polygon points="253,253 253,295"  stroke="#58D3F7" stroke-width="4"/>
    <polygon points="348,488 403,488"  stroke="#58D3F7" stroke-width="4"/>
    </g>
    <g id="instalacja-h20-ciepla">
    <polygon points="110,39 424,39"  stroke="#FA5858" stroke-width="4"/>
    <polygon points="344,39 344,488"  stroke="#FA5858" stroke-width="4"/>
    <polygon points="246,248 346,248"  stroke="#FA5858" stroke-width="4"/>
    <polygon points="249,253 249,295"  stroke="#FA5858" stroke-width="4"/>
    <polygon points="348,484 403,484"  stroke="#FA5858" stroke-width="4"/>
    </g>

    <g id="instalacja-kanalizacja">
    <polygon points="110,48 425,48"  stroke="#8A0829" stroke-width="8"/>
    <polygon points="168,48 168,265"  stroke="#8A0829" stroke-width="8"/>
    <polygon points="168,265 342,265"  stroke="#8A0829" stroke-width="8"/>
    <polygon points="235,268 235,293"  stroke="#8A0829" stroke-width="8"/>
    </g>

    <!--<g id="instalacja-elektyka">

        <g id="elektryka-sypialnia">
                <polygon points="929,464 928,397"  stroke="#0B610B" stroke-width="2"/>
                <polygon points="687,461 929,464"  stroke="#0B610B" stroke-width="2"/>
                <polygon points="687,44 687,461"  stroke="#0B610B" stroke-width="2"/>
                <polygon points="690,220 800,220"  stroke="#0B610B" stroke-width="2"/>
                <polygon points="357,35 687,35"  stroke="#0B610B" stroke-width="2"/>
                <circle cx="686" cy="334" r="4" stroke="#0B610B" stroke-width="1" fill="#0B610B"  data-alt="wyłącznik"/>
                <circle cx="800" cy="220" r="10" stroke="#0B610B" stroke-width="1" fill="#fff"/>
                <rect y="397" x="926" width="8" height="8" fill="#0B610B" stroke="#0B610B"/>
                <rect y="200" x="684" width="8" height="8" fill="#0B610B" stroke="#0B610B"/>
        </g>
        
        <g id="elektryka-kuchnia">
             <rect x="662" y="90" width="8" height="8" fill="#0B610B" stroke="#0B610B"/>
             <rect x="350" y="65" width="8" height="8" fill="#0B610B" stroke="#0B610B"/>
             <rect x="394" y="224" width="8" height="8" fill="#0B610B" stroke="#0B610B"/>
             <rect x="552" y="44" width="8" height="8" fill="#0B610B" stroke="#0B610B"/>
             <rect x="670" y="322" width="8" height="8" fill="#0B610B" stroke="#0B610B"/>
             <circle cx="510" cy="220" r="10" stroke="#0B610B" stroke-width="1" fill="#fff"/>
             <circle cx="394" cy="340" r="4" stroke="#0B610B" stroke-width="1" fill="#0B610B" />
              <polygon points="393,220 500,220"  stroke="#0B610B" stroke-width="2"/>
              <polygon points="393,220 393,340"  stroke="#0B610B" stroke-width="2"/>
              <polygon points="357,35 357,141"  stroke="#0B610B" stroke-width="2"/>
        </g>
        
        <g id="elektryka-wc">
        <circle cx="198" cy="355" r="10" stroke="#0B610B" stroke-width="1" fill="#fff"/>
        <circle cx="235" cy="360" r="4" stroke="#0B610B" stroke-width="1" fill="#0B610B" />
        <rect x="232" y="345" width="8" height="8" fill="#0B610B" stroke="#0B610B"/>
        </g>
        
        <g id="elektryka-schody">
        <circle cx="96" cy="450" r="10" stroke="#0B610B" stroke-width="1" fill="#fff"/>
        <circle cx="145" cy="360" r="4" stroke="#0B610B" stroke-width="1" fill="#0B610B" />
        <rect x="142" y="345" width="8" height="8" fill="#0B610B" stroke="#0B610B"/>
        <polygon points="96,344 393,344"  stroke="#0B610B" stroke-width="2"/>
        <polygon points="96,344 96,441"  stroke="#0B610B" stroke-width="2"/>
        </g>
        
        <g id="elektryka-lazienka">
             <rect x="372" y="295" width="8" height="8" fill="#0B610B" stroke="#0B610B"/>
             <circle cx="373" cy="249" r="10" stroke="#0B610B" stroke-width="1" fill="#fff"/>
             <circle cx="222" cy="135" r="10" stroke="#0B610B" stroke-width="1" fill="#fff"/>
              <circle cx="376" cy="288" r="4" stroke="#0B610B" stroke-width="1" fill="#0B610B" />
              <circle cx="354" cy="330" r="4" stroke="#0B610B" stroke-width="1" fill="#0B610B" />
              <polygon points="235,137 339,137"  stroke="#0B610B" stroke-width="2"/>
             </g>
    </g>-->
    <!-- teksty -->


    <!-- tekst sien -->    
    <text x="140" y="30">w:66x160</text>

    <text x="46" y="290">110x305=3.5</text>
    <text x="46" y="320">schody piwnica</text>
    <text x="535" y="380">schody strych</text>

    <text x="166" y="400">WC 1.8</text>
    <text x="166" y="420">215x80</text>

    <!-- tekst spizarka --> 
    <text x="355" y="30">w:160x160</text>
    <text x="180" y="80">łazienka</text>
    <text x="180" y="120">100x300=3</text>
    <text x="180" y="150">180x90=1.6</text>
    <text x="100" y="100">180x90=1.2+1.6+3=5.8</text>

    <!-- tekst łazienka --> 
    <text x="470" y="180">kuchnia</text>
    <text x="470" y="120">320x150 = 5</text>
    <text x="470" y="150">277x150 = 4+5=9</text>

    <!-- tekst kuchnia --> 
    <text x="735" y="35">w:90x230</text>
    <text x="690" y="80">sypialnia</text>
    <text x="690" y="120">240x420=10.5</text>

    <!-- tekst przedpokój --> 
    <text x="280" y="360">przedpokój</text>
    <text x="280" y="390">120x420=5</text>

    <!-- tekst salon --> 
    <text x="225" y="930">w:162x230</text>
    <text x="190" y="850">sypialnia</text>
    <text x="190" y="880">405x416=16.85</text>
    <text x="300" y="482">w:88</text>

    <!-- tekst sypialnia -->    
    <text x="685" y="940">w:162x230</text>
    <text x="650" y="870">salon</text>
    <text x="650" y="890">456x416=18.96</text>    
    <text x="525" y="482">w:90</text>


    <text x="1055" y="425">schody</text> 
    <text x="1055" y="485">w:95x200</text>
    <text x="1095" y="805">w:120x200</text>
    <text x="925" y="655">w:90 x210</text>
    
    
    <text x="1055" y="585">hol 310 x 275 =8.5 </text>

    <text x="1105" y="925">taras 3.5 x 1.20 = 4.2</text>

    <!-- tekst stodoła --> 

    <text x="1000" y="80">wyburzenie</text>
    <text x="1000" y="120">351x462=~16</text> 
    
    <text x="417" y="70">zlew 80x60</text>
    <text x="50" y="70">brodzik 90x90</text>
    
    <text x="400" y="250">piec induk. 60x60</text>
    
    <text x="194" y="211">wc</text>
<text x="175" y="280">wc</text>

    <g class="wywierzniki">
    <rect stroke="black" fill="yellow" height="40" width="40" x="406" y="490"/>
    <text x="412" y="515">CO</text> 

    <rect stroke="black" fill="yellow" height="15" width="15" x="158" y="232"/>
    <text x="160" y="245">WC,O2</text> 

    <rect stroke="black" fill="yellow" height="15" width="15" x="370" y="200"/>
    <text x="347" y="215">02</text>
    </g>
    </svg>     
</section>

<?php $this->ob(); ?>
<script src="/js/mig/mig.canvas.view.js"></script>
<script type="text/javascript">
    // <![CDATA[

    mig.canvas.view(window, {});
    // ]]>
</script>
<?php $this->clean(); ?>
    