<section> 
    <?php $this->render('projection/view/partial/tools.phtml'); ?>
     <div class="list-switcher">
      <a href="#" class="switcher" data-id-to-switch="lukarna-zachod">pokaż lukarna zachod</a>
     <a href="#" class="switcher" data-id-to-switch="lukarna-srodkowa">pokaż lukarna srodkowa</a>
     <a href="#" class="switcher" data-id-to-switch="lukarna-wschod">pokaż lukarna wschod</a>
     </div> 
     
   <svg  version="1.1"
         baseProfile="full"
         accesskey=""
        class="svg-canvas"
         viewBox="0 0 968 945"
         width="968" 
         height="945">
<?php $this->render('projection/view/partial/style.phtml'); ?>
  
  <rect  x="0" y="0" width="968" height="945" fill="#ccc" stroke="black"/>
  <rect  x="42" y="42" width="884" height="861" fill="#fff" stroke="black"/>
  
  
 <!-- <rect  x="42" y="42" width="1236" height="162" fill="transparent" stroke="black"/>-->
  <!-- <line x1="42" y1="92" x2="924" y2="92" stroke-width="2" stroke="red"/> -->
  <line x1="42" y1="240" x2="924" y2="240" stroke-width="2" stroke="orange"/> 
   
  
  <!-- <line x1="42" y1="853" x2="924" y2="853" stroke-width="2" stroke="red"/> -->
  <line x1="42" y1="705" x2="924" y2="705" stroke-width="2" stroke="orange"/>
  
  <rect  x="42" y="42" width="884" height="73" fill="#dfdfdf" stroke="orange"/>
  <rect  x="42" y="93" width="884" height="20" fill="#fff" stroke="black"/>
    <!-- strop -->
  
  
  <!-- schody -->
  <rect  x="42" y="172" width="85" height="289" fill="#fffccc" stroke="black"/>
  <rect  x="128" y="372" width="112" height="90" fill="#fffccc" stroke="black"/>
  
  <rect  x="42" y="830" width="884" height="73" fill="#dfdfdf" stroke="orange"/>
  
  <rect  x="42" y="830" width="884" height="20" fill="#fff" stroke="black"/>
  
  <!-- sciany nosne -->
  
  <rect  x="42" y="462" width="884" height="20" fill="#ccc" stroke="black"/> <!-- nosna -->
  <rect  x="456" y="480" width="20" height="350" fill="#ccc" stroke="black"/><!-- nosna ?  salon -->
  
  <!-- kominy -->
  <rect  y="490" x="475" width="16" height="22" fill="#ccc" stroke="black"/>
  
  
  <!-- sciany dzialowe -->
  <rect  y="115" x="370" width="12" height="210" fill="#fff" stroke="black"/><!-- dzialowa sien -->  
   
  
   
   <rect  y="152" x="42" width="105" height="20" fill="#fff" stroke="black"/>
   <rect  y="172" x="128" width="20" height="200" fill="#fff" stroke="black"/>
   <rect  y="352" x="148" width="112" height="20" fill="#fff" stroke="black"/>
   
   <rect  y="322" x="260" width="345" height="12" fill="#fff" stroke="black"/>
   
  <rect  y="115" x="604" width="12" height="348" fill="#ccc" stroke="black"/><!-- dzialowa lazienka -->
  
 <!-- <rect  y="42" x="926" width="20" height="861" fill="#ccc" stroke="black"/> dzialowa kuchnia -->
  
  
  
   <!-- okna -->
   <rect  x="215" y="93" width="90" height="20" fill="#ffccff" stroke="black"/><!-- okno sien -->

  
   <rect  x="450" y="93" width="90" height="20" fill="#ffccff" stroke="black"/><!-- okno lazienka -->
   
   
   
  <rect  x="636" y="93" width="120" height="20" fill="#ffccff" stroke="black"/><!-- okno kuchnia -->
  
  
 
  
  <!--<rect class="lukarna-zachod"  x="175" y="903" width="90" height="42" fill="#ffccff" stroke="black"/> okno salon -->
  

  
  <!-- <rect  x="600" y="903" width="90" height="42" fill="#ffccff" stroke="black"/>okno sypialnia -->
  <rect  x="500" y="830" width="160" height="20" fill="#ffccff" stroke="black"/>
  
<rect  x="270" y="830" width="160" height="20" fill="#ffccff" stroke="black"/>
  
 
  
  
  <rect stroke="black" fill="#ffccff" height="90" width="42" x="0" y="545"/>
  <rect stroke="black" fill="grey" height="50" width="42" x="0" y="447.5"/>
  <rect stroke="black" fill="#ffccff" height="90" width="42" x="0" y="340"/>
  


  <rect  x="248" y="322" width="12" height="30" fill="#fff" stroke="black"/>
   
   
  
  <!-- drzwi -->
  
  <rect  x="240" y="373" width="20" height="85" fill="#ffcccc" stroke="black"/><!-- drzwi sien -->
  <rect  x="404" y="322" width="85" height="12" fill="#ffcccc" stroke="black"/><!-- drzwi spizarka -->
  <rect  x="264" y="322" width="85" height="12" fill="#ffcccc" stroke="black"/>
  
  <rect  x="604" y="360" width="12" height="85" fill="#ffcccc" stroke="black"/>
     
   <rect  x="280" y="462" width="88" height="20" fill="#ffcccc" stroke="black"/><!-- drzwi salon -->
    <rect  x="500" y="462" width="90" height="20" fill="#ffcccc" stroke="black"/><!-- drzwi sypialnia -->
    
     <!-- nowe drzwi -->
  <rect  x="926" y="302" width="42" height="90" fill="#ffcccc" stroke="black"/><!-- okno sypialnia -->
  
  <rect  x="926" y="560" width="42" height="90" fill="#ffcccc" stroke="black"/>


    
    <!-- teksty -->
    
    
    <!-- tekst sien -->    
    <text x="230" y="90">w:90</text>
    <text x="50" y="230">w:90/85</text>
    
    <text x="60" y="140">garderoba</text>
    
  <text x="60" y="410">klatka schodowa</text>
    
    <!-- tekst łazienka --> 
    <text x="475" y="90">w:90</text>
    <text x="470" y="180">łazienka</text>
    
    
    <!-- tekst kuchnia -->
     <text x="650" y="90">w:120 x 100</text>
    <text x="670" y="180">kuchnia</text>
    <text x="670" y="140">310x420=13.02</text>
    
    <!-- tekst przedpokój --> 
    <text x="280" y="360">przedpokój</text>
    
    <!-- tekst salon --> 
    <text x="185" y="930">w:90</text>
    <text x="190" y="750">sypialnia</text>
    <text x="150" y="780">405x416=16.85</text>
    <text x="300" y="482">w:88</text>
    
     <!-- tekst sypialnia -->
     <text x="325" y="820">w:160 x 100</text>
     <text x="505" y="820">w:160 x 100</text>
    <text x="650" y="750">salon/sypialnia</text>
    <text x="650" y="780">456x416=18.96</text>    
    <text x="525" y="482">w:90</text>
    
 
    
    <text x="3" y="380">w:90xh:125</text>
    
    <text x="3" y="585">w:90xh:210</text>
     <text x="853" y="585">w:90xh:210</text>
     <text x="853" y="365">w:90xh:210</text>
    
    <text x="800" y="88" fill="red">skos < ~100</text>
    <text x="800" y="870" fill="red">skos < ~100</text>
    
    <text x="800" y="228" fill="orange">skos < ~210</text>
    <text x="800" y="725" fill="orange">skos < ~210</text>
    
     <g class="wywierzniki">
        <rect stroke="black" fill="yellow" height="40" width="40" x="560" y="260"/>
        <text x="570" y="290">CO</text> 

        <rect stroke="black" fill="yellow" height="15" width="15" x="458" y="42"/>
        <text x="475" y="60">WC</text> 
    </g>
</svg>     
</section>

<?php $this->ob(); ?>
<script src="/js/mig/mig.canvas.view.js"></script>
    <script type="text/javascript">
    // <![CDATA[
    // 
    // 
        //var canv = jQuery('#canvas');
   
   //console.log(canv);
   //
   mig.canvas.view(window, {
            
        });
    // ]]>
    </script>
    <?php $this->clean(); ?>
    