<section> 
    <?php $this->render('projection/view/partial/tools.phtml'); ?>
    
    <div class="list-switcher">
     <!--<a href="#" class="switcher" data-id-to-switch="balkon-poludnie">pokaż balkon południe</a>
     <a href="#" class="switcher" data-id-to-switch="balkon-polnoc">pokaż balkon północ</a>
     <a href="#" class="switcher" data-id-to-switch="kasacja">pokaż kasacja</a>-->
    </div> 
     
     
   <svg  version="1.1"
         baseProfile="full"
         accesskey=""
        class="svg-canvas"
         viewBox="0 0 945 958"
         width="945" 
         height="958">
<?php $this->render('projection/view/partial/style.phtml'); ?>
  
  <rect  x="0" y="0" width="945" height="958" fill="#ccc" stroke="black"/>
  <rect  x="0" y="0" width="945" height="428" fill="#ccffff" stroke="black"/>
 
   <rect  x="42" y="748" width="861" height="210" fill="#fff" stroke="black"/> 
   
   
   <rect  x="42" y="448" width="861" height="280" fill="#fff" stroke="black"/> 
   
   
   <polygon points="0,428 472.5,0 945,428" fill="#fff" stroke="black" />
   
   <!--<polygon points="296,158 274,178 671,178 649,158" fill="red" stroke="black"/>-->
   
   <polygon points="330,128 308,148 637,148 615,128" fill="red" stroke="black"></polygon>
   
   
   <!-- nowe elementy poddasze -->
   
  <!-- <rect  x="0" y="218" width="42" height="125" fill="red"  stroke="black"/>
   <rect  x="0" y="278" width="42" height="60" fill="red"  stroke="black"/>-->
    <!-- <rect  x="0" y="178" width="42" height="250" fill="red" stroke="black"/>
  <rect  x="903" y="178" width="42" height="250" fill="red" stroke="black"/>   
   <rect  x="903" y="218" width="42" height="210" fill="red"  stroke="black"/>
   
   <polygon points="0,198 0,178 296,158 286,178" fill="red" stroke="black"/>
   
  <polygon points="0,178 276,178 352,148   160,148" fill="#ffccff" stroke="black"/>
   
    <polygon points="647,158 669,178  950,198 950,178" fill="red" stroke="black"/>-->
    
    <!--<polygon points="667,178 950,178  785,108 592,108 " fill="#ffccff" stroke="black"/>-->
    
    
    <rect class="balkon-polnoc" x="340" y="303" width="90" height="125" fill="red"  stroke="black"/>
    
    <rect class="balkon-poludnie" x="515" y="218" width="90" height="210" fill="red"  stroke="black"/>
    
    <rect class="kasacja" x="447.5" y="318" width="50" height="110" fill="#fff"  stroke="black"/>
    <rect  x="425" y="763" width="95" height="195" fill="#ffccff"  stroke="black"/>
    <!-- grunt  -->
   <polygon points="0,958 425,958 0,877" fill="brown" stroke="black"/>  
    <polygon points="521,958 945,958 945,908" fill="brown" stroke="black"/>
    
    <!--<polygon points="42,728 462,728 462,445" fill="#fffccc" stroke="black"/>-->
    
    <polygon points="42,728 330,728 330,540" fill="#fffccc" stroke="black"/>
     <polygon points="142,728 330,728 330,540" fill="#fffccc" stroke="black"/>
    
    
    
    <rect  x="330" y="538" width="10" height="190" fill="red" stroke="black"/>
    <rect  x="330" y="538" width="132" height="10" fill="#fffccc" stroke="black"/>
    <rect  x="380" y="448" width="90" height="90" fill="#fffccc" stroke="black"/>
    
    <rect  x="462" y="448" width="28" height="280" fill="#fff" stroke="black"/>
    
    <!-- tekst piwnica --> 
    <text x="425" y="900">h:195,w:95</text>
    <text x="270" y="850">piwnica, h:210</text>
    
     <!-- tekst parter -->    
    <text x="230" y="500">parter, h:280</text>
    <text x="340" y="640">h:190</text>
    <text x="347" y="563">w:121</text>
    <text x="245" y="720">w:299/205</text>
    <text x="825" y="420">kąt: <?php echo round(rad2deg(acos(472.5/640)));?></text>
    
     <!-- tekst poddasze -->    
    <text x="90" y="380">poddasze, h:280</text>
    <text x="500" y="380">h:210,w:90</text>
 <text x="340" y="380">h:125,w:90</text>
   
 
    <text x="65" y="720">kąt: <?php echo round(rad2deg(atan(190/299)));?></text>
    <!-- <text x="165" y="720">kąt: <?php echo round(rad2deg(atan(190/205)));?></text>-->
     <text x="165" y="720">kąt: <?php echo round(rad2deg(atan(330/472.5)));?></text>
     
     <text x="242" y="665">schody metalowe</text>
     
     <!--http://calcoolator.pl/kalkulator_schodow.html -->
     <!-- tekst strych -->    
    <text x="425" y="100">strych, h:~128</text>
     
      <text x="425" y="145">h:~20</text>
      <text x="425" y="445">h:~20</text>
      <text x="425" y="745">h:~20</text>
      
      <text x="442" y="345">kasacja okna obecnego</text>
    
</svg>     
</section>

<?php $this->ob(); ?>
<script src="/js/mig/mig.canvas.view.js"></script>
    <script type="text/javascript">
    // <![CDATA[
    // 
    // 
        //var canv = jQuery('#canvas');
   
   //console.log(canv);
   //
   mig.canvas.view(window, {
            
        });
    // ]]>
    </script>
    <?php $this->clean(); ?>
    