<section> 
    <?php $this->render('projection/view/partial/tools.phtml'); ?>
    <div class="list-switcher">
      <a href="#" class="switcher" data-id-to-switch="lukarna">pokaż lukarna</a>
    </div>
   <svg  version="1.1"
         baseProfile="full"
         accesskey=""
        class="svg-canvas"
         viewBox="0 0 1320 958"
         width="1320" 
         height="958">
<?php $this->render('projection/view/partial/style.phtml'); ?>
  
  <rect  x="0" y="0" width="1320" height="958" fill="#ccc" stroke="black"  />
  
  <rect  x="0" y="0" width="1320" height="428" fill="#99ccff" stroke="black"/> 
 
   <rect  x="394" y="748" width="888" height="210" fill="#fff" stroke="black"/> 
   
   <rect  x="42" y="748" width="310" height="210" fill="grey" stroke="black"/>
   
   
   <rect  x="42" y="448" width="1236" height="280" fill="#fff" stroke="black"/>
   
     <!-- piwnica okna -->
    
    <rect  x="525" y="760" width="42" height="51" fill="#ffccff" stroke="black"/>
    <rect  x="1124" y="760" width="95" height="65" fill="#ffccff" stroke="black"/>
   
    
    <!-- okna strych -->
    <rect  x="404" y="30" width="50" height="50" fill="#ffccff" stroke="black"/>
   <rect  x="740" y="30" width="50" height="50" fill="#ffccff" stroke="black"/>
   
   
    <!-- okna poddasze -->
    <rect  x="173" y="218" width="90" height="125" fill="#ffccff" stroke="black"/>
    <rect  x="847" y="218" width="90" height="125" fill="#ffccff" stroke="black"/>
    <rect  x="1135" y="218" width="90" height="125" fill="#ffccff" stroke="black"/>
   
    <g class="lukarna">
    <rect  x="527" y="218" width="39" height="125" fill="#ccc" stroke="black"/>
   
   <rect  x="449" y="218" width="90" height="125" fill="red"  stroke="black"/>
   <rect  x="555" y="218" width="90" height="125" fill="red"  stroke="black"/>
   
   <rect  x="410" y="198" width="39" height="230" fill="#ccc"  stroke="black"/>
   <rect  x="645" y="198" width="39" height="230" fill="#ccc"  stroke="black"/>
   
   <rect  x="449" y="343" width="196" height="85" fill="#ccc" stroke="black"/>
   
   <rect  x="410" y="178" width="275" height="20" fill="#ccc"  stroke="black"/>
    <rect  x="410" y="198" width="275" height="20" fill="#ccc"  stroke="black"/>
   </g> 
   
   
   
   <g class="ganek">
   <rect  x="975" y="730" width="30" height="202" fill="#ccc" stroke="black"/>   
   <rect  x="1178" y="730" width="30" height="202" fill="#ccc" stroke="black"/>
  <rect  x="968" y="730" width="246" height="20" fill="#ccc" stroke="black"/>
  <polygon class="steps" points="787,858 970,858  970,730" fill="#cccfff" stroke="black"/>
  
  
  <rect  x="970" y="476" width="242" height="2" fill="#fff" stroke="black"/>
  <rect  x="970" y="478" width="2" height="250" fill="#fff" stroke="black"/>
  <rect  x="1210" y="478" width="2" height="250" fill="#fff" stroke="black"/>
  <rect  x="970" y="448" width="242" height="30" fill="#fff" stroke="black"/>
  
  </g>
   
   
   
    <!--scianki poddasze-->
   
    
    <rect  x="0" y="0" width="42" height="428" fill="#99ccff" stroke="black"/>
   <rect  x="1278" y="0" width="42" height="428" fill="#99ccff" stroke="black"/>
   <rect  x="0" y="158" width="1320" height="20" fill="#99ccff" stroke="black"/>
   
    <rect  x="362" y="178" width="20" height="250" fill="#99ccff" stroke="black"/>
   <rect  x="700" y="178" width="20" height="250" fill="#99ccff" stroke="black"/>
   <rect  x="1064" y="178" width="20" height="250" fill="#99ccff" stroke="black"/> 
    
    <!-- sciani parter -->
    <g class="scianki"> 
   <line x1="352" y1="448" x2="352" y2="728" stroke-width="1" stroke="black"/>
    <line x1="394" y1="448" x2="394" y2="728" stroke-width="1" stroke="black"/>    
    
    <line x1="704" y1="448" x2="704" y2="728" stroke-width="1" stroke="black"/>
    <line x1="716" y1="448" x2="716" y2="728" stroke-width="1" stroke="black"/>
    
    <line x1="862" y1="448" x2="862" y2="728" stroke-width="1" stroke="black"/>
    <line x1="874" y1="448" x2="874" y2="728" stroke-width="1" stroke="black"/>
    
    <line x1="1068" y1="448" x2="1068" y2="728" stroke-width="1" stroke="black"/>
    <line x1="1080" y1="448" x2="1080" y2="728" stroke-width="1" stroke="black"/>
    
    
    <line x1="704" y1="748" x2="704" y2="958" stroke-width="1" stroke="black"/>
    <line x1="716" y1="748" x2="716" y2="958" stroke-width="1" stroke="black"/>
    </g>
    
    
    
     <rect  x="1084" y="517" width="96" height="210" fill="#ffccff"  stroke="black"/>
     
     
    
   <rect  x="173" y="628" width="95" height="210" fill="#ffccff"  stroke="black"/>
    <rect  x="173" y="518" width="95" height="210" fill="red"  stroke="black"/>
    
    
    <!-- grunt  -->
   <polygon points="0,815 0,958 1320,958 1320,860" fill="brown" stroke="black"/>
    
   
   
    <rect  x="473" y="488" width="150" height="155" fill="red" stroke="black"/>
    <rect  x="487" y="488" width="122" height="160" fill="#ffccff" stroke="black"/>
    
    <rect  x="778" y="488" width="55" height="160" fill="#ffccff" stroke="black"/>
    <rect  x="778" y="488" width="55" height="155" fill="#ffccff" stroke="black"/>
    <rect  x="900" y="488" width="55" height="160" fill="#ffccff" stroke="black"/>
    <rect  x="900" y="488" width="55" height="155" fill="#ffccff" stroke="black"/>
    <!-- kominy -->
   
   <rect  x="808" y="0" width="30" height="50" fill="#666" stroke="black"/>
   <rect  x="352" y="0" width="30" height="50" fill="#666" stroke="black"/>   
    <rect  x="716" y="110" width="30" height="50" fill="#666" stroke="black"/>
   
    
  <text x="875" y="816">kąt: <?php echo round(rad2deg(atan(105/185)));?>, h:105,w:185</text>
    
    
   <!-- 
   sien sciana i schody
   
   <rect  x="1187" y="448" width="90" height="280" fill="#fffccc" stroke="black"/>
    
    <rect  x="1068" y="448" width="12" height="280" fill="#ccc" stroke="black"/>-->
    
    <!-- tekst piwnica --> 
    <text x="179" y="593">h:210,w:95</text>
    <text x="1082" y="593">h:210,w:95</text>
    
    <text x="482" y="593">h:160(155),w:150</text>
    <text x="782" y="563">h:160(155),w:55</text>
    <text x="909" y="593">h:160(155),w:55</text>
    
     <text x="1082" y="745">w:246x190</text>
    
    <text x="720" y="770">piwnica, h:210</text>
    
    <text x="500" y="810">w:42, h:51</text>
    <text x="1082" y="810">w:95, h:65</text>
    
     <!-- tekst parter -->    
    <text x="80" y="500">parter, h:280</text>
    
     <!-- tekst poddasze -->    
   
    <text x="490" y="300">h:125x90x2</text>
    
     <text x="490" y="380">h:85</text>
     
     <text x="80" y="380">h:250(280) poddasze</text>
     
          <text x="80" y="80">h:158 strych</text>

     <!--        lukarna wersja 2             -->
     
     <text x="10" y="580">cegła+ubijany hash</text>
     <text x="320" y="380">"regips"</text>
     <text x="690" y="580">cegła</text>
     
     
     
   <!-- <text x="845" y="300">h:210x90x2</text>
    <text x="130" y="140">daszek lukarna,h:~70</text>-->
    
     <!-- tekst strych -->      
      <text x="455" y="195">h:~20x2 strop drewniany</text>
      <text x="425" y="445">h:~20 strop drewniany</text>
      <text x="425" y="745">h:~20 strop żelbetowy</text>
   
    
</svg>     
</section>


<svg version="1.1"
         baseProfile="full"
         accesskey=""
        class="svg-view"
         viewBox="0 0 1690 1000"
         width="1690" 
         height="1000">

</svg>




<?php $this->ob(); ?>
<script src="/js/mig/mig.canvas.view.js"></script>
    <script type="text/javascript">
    // <![CDATA[
    // 
    // 
        //var canv = jQuery('#canvas');
   
   //console.log(canv);
   //
   mig.canvas.view(window, {
            
        });
    // ]]>
    </script>
    <?php $this->clean(); ?>

    
    
    <svg width='280' height='280'
     xmlns='http://www.w3.org/2000/svg' 
     xmlns:xlink='http://www.w3.org/1999/xlink'
     onload='init(evt)' > 
 
  <style> 
    .edge{
        fill: white;
        stroke: black;
        stroke-width: 1;
    }
    .button{
        fill: #2060dd;
        stroke: #2580ff;
        stroke-width: 1;
    }
    .button:hover{
        stroke-width: 3;
    }
  </style> 
 
  <script type='text/ecmascript'> 
    <![CDATA[

    edges = [[0,1],[2,3],[0,2],[1,3],[4,5],[6,7],[4,6],[5,7],[0,4],[1,5],[2,6],[3,7]]
    x_coords = [50,190,50,190,50,190,50,190];
    y_coords = [50,50,190,190,50,50,190,190];
    z_coords = [50,50,50,50,190,190,190,190];
    
    centre_x = 120;
    centre_y = 120;
    centre_z = 120;
    
    function init(evt)
    {
        if ( window.svgDocument == null )
        {
            svgDocument = evt.target.ownerDocument;
        }
        drawBox();
    }
    
    function drawBox()
    {
        for(var i=0; i<edges.length; i++)
        {
            edge = svgDocument.getElementById('edge-'+i);
            edge.setAttributeNS(null, 'x1', x_coords[edges[i][0]]);
            edge.setAttributeNS(null, 'x2', x_coords[edges[i][1]]);
            edge.setAttributeNS(null, 'y1', y_coords[edges[i][0]]);
            edge.setAttributeNS(null, 'y2', y_coords[edges[i][1]]);
        }
    }
    
    function rotateAboutX(radians)
    {
        for(var i=0; i<x_coords.length; i++)
        {
            y = y_coords[i] - centre_y;
            z = z_coords[i] - centre_z;
            d = Math.sqrt(y*y + z*z);
            theta  = Math.atan2(y, z) + radians;
            y_coords[i] = centre_y + d * Math.sin(theta);
            z_coords[i] = centre_z + d * Math.cos(theta);
        }
        drawBox();
    }
    
    function rotateAboutY(radians)
    {
        for(var i=0; i<x_coords.length; i++)
        {
            x = x_coords[i] - centre_x;
            z = z_coords[i] - centre_z;
            d = Math.sqrt(x*x + z*z);
            theta  = Math.atan2(x, z) + radians;
            x_coords[i] = centre_x + d * Math.sin(theta);
            z_coords[i] = centre_z + d * Math.cos(theta);
        }
        drawBox();
    }
    
    function beginRotateX(radians)
    {
        rotateAboutX(radians);
        rotateX_timeout = setInterval("rotateAboutX(" + radians + ")", 20);
    }
    
    function endRotateX()
	{
        if (typeof(rotateX_timeout) != "undefined")
        {
            clearTimeout(rotateX_timeout);
        }
	}
    
    function beginRotateY(radians)
    {
        rotateAboutY(radians);
        rotateY_timeout = setInterval("rotateAboutY(" + radians + ")", 20);
    }
    
    function endRotateY()
	{
        if (typeof(rotateY_timeout) != "undefined")
        {
            clearTimeout(rotateY_timeout);
        }
	}
    
    ]]>
  </script> 
 
    <line id='edge-0' class='edge' x1='100' y1='100' x2='100' y2='100'/>
    <line id='edge-1' class='edge' x1='100' y1='100' x2='100' y2='100'/>
    <line id='edge-2' class='edge' x1='100' y1='100' x2='100' y2='100'/>
    <line id='edge-3' class='edge' x1='100' y1='100' x2='100' y2='100'/>
    <line id='edge-4' class='edge' x1='100' y1='100' x2='100' y2='100'/>
    <line id='edge-5' class='edge' x1='100' y1='100' x2='100' y2='100'/>
    <line id='edge-6' class='edge' x1='100' y1='100' x2='100' y2='100'/>
    <line id='edge-7' class='edge' x1='100' y1='100' x2='100' y2='100'/>
    <line id='edge-8' class='edge' x1='100' y1='100' x2='100' y2='100'/>
    <line id='edge-9' class='edge' x1='100' y1='100' x2='100' y2='100'/>
    <line id='edge-10' class='edge' x1='100' y1='100' x2='100' y2='100'/>
    <line id='edge-11' class='edge' x1='100' y1='100' x2='100' y2='100'/>
    
    <path class="button"
          d="m50.5 250.5 15 -15 0 8 45 0 0 14 -45 0 0 8 z"
          onmousedown='beginRotateY(0.08)'
          onmouseout='endRotateY()'
          onmouseup='endRotateY()'/>
          
    <path class="button"
          d="m190.5 250.5 -15 -15 0 8 -45 0 0 14 45 0 0 8 z"
          onmousedown='beginRotateY(-0.08)'
          onmouseout='endRotateY()'
          onmouseup='endRotateY()'/>
          
    <path class="button"
          d="m255.5 50.5 15 15 -8 0 0 45 -14 0 0 -45 -8 0 z"
          onmousedown='beginRotateX(0.08)'
          onmouseout='endRotateX()'
          onmouseup='endRotateX()'/>
          
    <path class="button"
          d="m255.5 190.5 15 -15 -8 0 0 -45 -14 0 0 45 -8 0 z"
          onmousedown='beginRotateX(-0.08)'
          onmouseout='endRotateX()'
          onmouseup='endRotateX()'/>
    
</svg>
    