<section>
    
    <div class="review-text">
        <!--<h4 class="head-title review-title">Remont domu - materiały zebrane:</h4>
        
         <div class="list-switcher"> 
     <a href="#" class="switcher" data-id-to-switch="opis">Opis domu</a>
     <a href="#" class="switcher" data-id-to-switch="prace">prace do wykonania</a>
    </div>
        
        <p class="p-text review-description">Opis domu do remontu.
        
        
 <br>
<br>-->
        
        <div  class="opis">
       
       
       <h4 class="aside-title">Opis budynku:</h4>
  <p class="p-text">
     Jest to budynek parterowy podpiwniczony wybudowany w latach około 1958 - 1960,   z piwnicami tylko pod częścią mieszkalną. Do części mieszkalnej przylega pomieszczenie gospodarcze , 
     <br>które kiedyś było stodołą.</p>


  <ul>
      <li>Piwnice wystają z gruntu na około od 60 do 160cm, </li>
      <li>wysokość piwnic: 210cm, </li>
      <li>wysokość parteru 280cm, </li>
      <li>poddasze bez ścianki kolankowej, </li>
          <li>kąt nachylenia dachu około 42 stopnie,</li>
          <li>wysokość ścian szczytowych to około 4,28cm.</li>
          <li> Ściany szczytowe domu są na osi wschód-zachód.</li>
          <li> fundamenty to układany kamień na zaprawie cementowej po zewnętrznej części a w środku mieszany pustak(betonowy?) + cegla - nie znam ich głębokości</li> 
  </ul>
  
  <p class="p-text">
      
     <br>
Dom posiada mury zewnętrzne dwuwarstwowe, warstwa zewnętrzna cegła pełna, wewnątrz mieszana cegła pełna,pustak zużlowy/haszowy, ubijany hasz, grubość całości 42cm.
 </p>
 
  <p class="p-text">

Piwnice posiadają mury z pustaka betonowego(częściowo cegły) oraz 2 rodzaje stropów nad piwnicami:</p>
  
  <ul>
      <li>nad 2 pokojami strop Kleina:<br>
          - wymiary 420x405 - 3 teowniki długości 410cm  ,<br>
- wymiary 420x456 - 3 teowniki długości 456cm, <br>
- rozstaw 100cm <br>
- szerokość teownika 11 cm, wysokość nieznana, grubość około 4-5mm(??), przestrzeń pomiędzy teownikami wypełniona jest cegłą i otynkowana. <br>
 - Nad tymi stropami znajduje się podłoga na legarach, <br>
 - materiał wypełniający to zaprawa wapienno piaskowa<br>
 - Jedna piwnica do około 1975 r. była stajnią ,  tutaj teownik jest najbardziej skorodowany<br>
 - druga od około 10lat miała ocieplony od strony piwnicy strop styropianem grubości około 2-3cm. po usuunięciu ocieplenia teownik okazał się mniej skorodowany w porównaniu do  drugiej piwnicy
</li> 
 <li>Teowniki są skorodowane (nie znam grubości skorodowania). </li>
  <li>     
Reszta stropów jest żelbetowa, pod łazienką jest mocno zniszczony</li>

</ul>
  
  <p class="p-text">
Pomieszczenie gospodarcze kiedyś było stodołą o wymiarach  320x840cm, to pomieszczenie podzielone jest fundamentem na dwie części.<br>

w 1. części wysokość 345 x 420 x 320cm  + wysokosć  ścian szczytowych 4.28m <br>
w 2 część: wysokość 280 x 420 x 320cm  + wysokosć  ścian szczytowych 4.28m <br>

to pomioeszczenie ma otwartą przestrzenią do  ściany szczytowej, brak okna, są tylko drzwi wejściowe szer 90cm x210cm, <br>
ściana północna kiedyś była drewnianą bramą wejściową, obecnie ten fragment zamurowany jest jednowarstwowym pustakiem haszowym z pozostawionym otworem na drzwi jw. <br>
Ściany tego pomieszczenia wykonane są z mieszanego materiału są jednowarstwowe z pustaka, pełnej cegły i ubijanego haszu. <br>
W połowie pomieszczenia wykonany jest fundament wysokości około  ~ 60-80cm ponad grunt.
</p> 
 
 

        
    </div>

  <div  class="prace">
      
      <h4 class="aside-title">Prace do wykonania:</h4>
      
     
          
      <ul>
<li>  Wzmocnie stropów Klein'a:
  <br>  <br>
Wzmocnienie samych teowników od dołu, od góry: usunięcie  podłogi, resztek starego wypełnienia, wysypanie kuleczek keramzytowych, <br>
nowe legary co 50cm + podłoga  legary będą gęściej niż jest to obecnie (podłoga się ugina, legary są co 1m wzdłuż teowników położone)  - lepsza byłaby wylewka jeśli jest taka możliwość ??<br>

</li>
<li>wzmocnienie stropu żelbetowego o powierzchni 3.5m2</li>
<li> Nowy strop drewniany?? może uda się coś lepszego ??) nad parterem  i nowa więźba dachowa, pokrycie dachowe (dachówka??):
 <br><br>
 Będzie to odtworzenie obecnie istniejących(obecne mają "kornika") – (te same parametry, kąt nachylenia, wysokość itp..), <br>
</li>
<li> Ocieplenie i izolacja przeciwwilgociowa murów domu  wraz z fundamentami piwnic i posadzką (obecnie brak ocieplenia poziomego piwnic i izolacji przeciwwilgociowej )</li>
<li>Adaptacja na cele mieszkaniowe poddasza, <br>
    
    - nowe dwa otwory na drzwi balkonowe i okno w istniejącej zachodniej ścianie szczytowej, <br>
    - nowa wschodnia ściana szczytowa(obecnie brak) a w niej również dwa otwory na drzwi balkonowe, i mały wiszący balkon (1x2m jeśli byłaby taka możliwość??)<br>
    - ścianka kolankowa na wysokość 1m cofnięta do środka budynku<br>
    - <s>dwie lukarny proste, jedna byłyby to okna  ustawione na konstrukcji  dachu(ściance kolankowej) obudowane płytami OSB i ocieplone a
    druga lukarna to wymurowana na murach na wysokość około 1m ścianka kolankowa na niej osadzone okna obudowane płytą osb.</s>
<br/>zmiana na okna połaciowe(mniejsze obciążenie i koszty wykonania na rzecz, <u>jeśli byłaby taka możliwość</u>, stropu( niedrewnanego) i poszycia z dachówek ?? <br>
    
<br> Ściany działowe wybudowane z pustaków keramzytowych ewentualnie tylko z tkz. regipsów<br>
 
<?php /*Jaki byłby procentowy szacunkowy koszt lukarn jak na zrzutach  wobec całkowitego kosztu wykonania samego dachu ?*/?>
 </li>
 
<?php /* <li> Nowe schody  prowadzące na poddasze z obecnej sieni(pomieszczenie zachodnie) <br>
 
 Wtedy ewentualnie strop nad łazienkami i przedpokojem (+ sień) na którym wspierałyby się schody należałoby zrobić żelbetowy, keramzytowy itp.. (??)
 <br>
 
 Gdyby stan fundamentów itd... nie pozwalał na to wtedy stropy i schody byłyby tylko drewniane. 
 
 </li>
 


 
 <li>Adaptacja pomieszczenia gospodarczego:
  <br><br>
Byłby to otwarty pokój: salon-przedpokój z wejściem dla gości od północy  i wyjściem do ogrodu. Wymiary: 8,40 x 3,10m = 25,2m2.
 <br><br>
3a. Ściana południowa: należy wykuć otwór pod drzwi balkonowe (90x230 ) i okno (90x160cm)  w ścianie jednowarstwowej zewnętrznej/nośnej, czy jest taka możliwość (wysokosc nad nadprozem to jedynie około 70cm muru)?
  <br>
3.b. Ściana wschodnia: należy wykuć otwór pod okno (160x160) 

3.c w zabudowanym obecnie otworze po bramie wykuć otwór pod okno balkonowe( które jednocześnie będą pełnić rolę drzwi wejściowych : 90x230) , <>br>
to będzie tylko powyższenie tego okna o około 1m bo obecnie otwór prowadzi do budynku wprost z gruntu a po zmianie powinien prowadzić z podwyższonego fundamentu
 <br>
3.c. Nowy fundament długości 4,20 po drugą warstwę ściany, reszta fundamentów pod nowe ściany jest
  <br>
3.d. Wymurowanie: drugiej warstwy ścian wewnętrznych (pustak keramzytowy? Porotherm ? grubości 20cm??)
 <br>
3.e. Ubicie gruntu pod posadzką, posadzki itd..
 <br>
 3f. wykucie drzwi 90x210 do obecnej części mieszkalnej w murze o grubości 42cm, wysokość nadproża około 70cm
 </li>
 <li>
    Schody o wysokości 135cm prowadzące z obecnego pomieszczenia gospodarczego do ogrodu z tarasem  na gruncie o wymiarach 3.10 x 2m
</li>
 <li>
    Schody o wysokości 70cm prowadzące do obecnego pomieszczenia gospodarczego od frontu północnego z podestem  na gruncie o wymiarach 1.20 x 1m
</li>*/?>
 <li>przebudowa ganku z obecnego blaszanego na murowany</li>
 <li>Rozbiórka pomieszczenia gospodarczego ~24m2,  pozostałyby tylko fundamenty a na podniesionym fundamencie można by zrobić niezadaszony taras w przyszłości. <br /><br /></li>
 <li>wyburzenie otworu drzwiowego 230x90cm w ścianie wschodniej parteru, będzie to wyjście z pokoju na taras</li>
 <li>wyburzenie otworu drzwiowego 230x160cm w ścianie nośnej parteru, będzie to połączenie pokoju(salonu) z kuchnią w celu powiększenia salonu na rzecz zmniejszenia kuchni </li>
      </ul>
      
       <?php /*<p class="p-text">
Proszę o podanie kosztów projektu każdego etapu z osobna.
 <br>
Czy takie zmiany wymagają pozwolenia na budowę czyli nadzoru budowlanego, kierownika budowy, przedłożenia w starostwie wymaganych dokumentów itp.. Proszę o listę tych dokumentów?
     <br>
      
 
Nowe otwory wykuwane by były w ścianach które mają wysokość 280cm, wysokość drzwi to 230/210cm (okien 160), <br>
więc ponad drzwiami zostałoby tylko 70/50cm wysokości muru, <br>
na poddaszu nie ma ścianki która odddziela byłą stodołę od domu. <br>
Jedynie okno na wschodniej ścianie miałoby nad sobą kalenicę. <br>



   <br>



Czy dużo większe koszty byłyby gdyby na poddaszu dorobić lukarny(jak na zrzutach i czy taka dobudowa zmieniłaby charakter remontu ze zgłoszenia na wymagane pozwolenie na budowę dla obecnej części mieszkalnej?
 <br>


Lukarny obudowane  konstrukcją drewnianą lub pustakami keramzytowymi? (aby ścianki były lekkie), wysokość poddasza 250cm wedłu zrzutów jednk po przemyśleniu tematu muszę zmienić na zrzutach na wysokość 280 cm.       
      <br><br>
  

  
</p>    */?>  
      
     
        <h4 class="aside-title">Galeria zdjęć:</h4>   
      
      <p class="p-text">W  <a href="/galeria">galerii </a> zdjęcia więźby dachowej , fragmenty stropu Kleina oraz pogłądowe rysunki/zdjęcia jak wyobrażam sobie dobudowane lukarny.</p>
      
      <br/><br/>
          <h4 class="aside-title">Rzuty:</h4> 
      <ul>
          <li class="main">stan istniejący
              <ol>
          <li><a href="/rzut,k,parter-inwent">rzut parteru </a></li>
          <li><a href="/rzut,k,poddasze-inwent">rzut poddasza </a></li> 
          <li><a href="/rzut,k,piwnica">rzut piwnic </a></li> 
          
           <li><a href="/rzut,k,przekroj-wschod-inwent">Rzut przekroju wschodniego </a></li> 
           <li><a href="/rzut,k,przekroj-zachod-inwent">Rzut przekroju zachodniego </a></li> 
           
           <li><a href="/rzut,k,front-polnoc-luk-inwent">Rzut frontu północnego </a></li> 
           <li><a href="/rzut,k,front-poludnie-inwent">Rzut frontu południowego </a></li>
           </ol>
          </li> 
           
          <li  class="main">stan po remoncie
              <ol>
          <li><a href="/rzut">rzut parteru po remoncie </a></li>  
          <li><a href="/rzut,k,poddasze">rzut poddasza po remoncie </a></li>
           <li><a href="/rzut,k,przekroj-wschod">przekrój wschodni po remoncie </a></li>  
          <li><a href="/rzut,k,przekroj-zachod">przekrój zachodni po remoncie </a></li>
          <li><a href="/rzut,k,front-poludnie-luk">front południowy po remoncie </a></li>
          
          <li><a href="/rzut,k,front-polnoc-luk">front północnego po remoncie </a></li>
          
          <li>reszta rzutów projektu w przygotowaniu</li>
          </ol>
          </li>
      </ul>
  
  
  
  
  </div>
        
        
   
</section>

<?php $this->ob(); ?>
<script src="/js/mig/mig.switcher.dom.js"></script>
    <script type="text/javascript">
    // <![CDATA[
    // 
    // 
        //var canv = jQuery('#canvas');
   
   //console.log(canv);
   //
  mig.switcher.dom(window, {
            
        });
    // ]]>
    </script>
    <?php $this->clean(); ?>