<section> 
    <?php $this->render('projection/view/partial/tools.phtml'); ?>
   <div class="list-switcher">
     <a href="#" class="switcher" data-id-to-switch="daszek">pokaż daszek</a>
   </div>  
   <svg  version="1.1"
         baseProfile="full"
         accesskey=""
        class="svg-canvas"
         viewBox="0 0 1320 958"
         width="1320" 
         height="958"
         >
 <?php $this->render('projection/view/partial/style.phtml'); ?>
  
  <rect  x="0" y="0" width="1320" height="958" fill="#ccc" stroke="black"/>
  
  <rect  x="0" y="0" width="1320" height="428" fill="#ffccff" stroke="black"/> 
 
   <rect  x="333" y="748" width="945" height="210" fill="#fff" stroke="black"/> 
   
   
   <rect  x="42" y="448" width="1236" height="280" fill="#fff" stroke="black"/> 
   
    
   <rect  x="435" y="198" width="39" height="230" fill="#ccc"  stroke="black"/>
   <rect  x="623" y="198" width="39" height="230" fill="#ccc"  stroke="black"/>
   
   <rect  x="473" y="348" width="150" height="80" fill="#ccc" stroke="black"/>
   
   <rect  x="973" y="730" width="246" height="20" fill="#ccc" stroke="black"/>
   
   <rect  x="993" y="730" width="30" height="202" fill="#ccc" stroke="black"/>
   
   <rect  x="1183" y="730" width="30" height="202" fill="#ccc" stroke="black"/>
   
  
    
    <polygon class="daszek" points="400,178 703,178  555,68 550,68 " fill="#ffccff" stroke="black"/>
    
    
    <rect  x="435" y="178" width="228" height="20" fill="#ccc"  stroke="black"/>
    <rect  x="435" y="198" width="228" height="20" fill="#ccc"  stroke="black"/>
    
     <rect  x="1083" y="517" width="96" height="210" fill="#ffccff"  stroke="black"/>
    <rect  x="473" y="218" width="150" height="130" fill="red"  stroke="black"/>
    
   
   
    <rect  x="173" y="518" width="95" height="210" fill="red"  stroke="black"/>
    <!-- grunt  -->
   <polygon points="0,815 0,958 1320,958 1320,860" fill="brown" stroke="black"/>
    
   
    <rect  x="473" y="488" width="150" height="160" fill="#ffccff" stroke="black"/>
    
    <rect  x="778" y="488" width="55" height="160" fill="#ffccff" stroke="black"/>
    <rect  x="900" y="488" width="55" height="160" fill="#ffccff" stroke="black"/>
   
    
    <!-- piwnica okna -->
    <rect  x="525" y="775" width="42" height="51" fill="#ffccff" stroke="black"/>
    <rect  x="1082" y="775" width="95" height="65" fill="#ffccff" stroke="black"/>
    
    
 
    
    <!-- tekst piwnica --> 
    <text x="179" y="593">h:210,w:95</text>
    <text x="1082" y="593">h:210,w:95</text>
    
    <text x="482" y="593">h:160,w:150</text>
    <text x="782" y="593">h:160,w:55</text>
    <text x="909" y="593">h:160,w:55</text>
    
     <text x="1082" y="745">w:246x190</text>
    
    <text x="670" y="810">piwnica, h:210</text>
    
    <text x="500" y="810">w:42, h:51</text>
    <text x="1082" y="810">w:95, h:65</text>
    
     <!-- tekst parter -->    
    <text x="290" y="550">parter, h:280</text>
    
     <!-- tekst poddasze -->    
   
    <text x="490" y="300">h:130x150</text>
    
     <text x="490" y="380">h:80</text>
     
     <text x="380" y="380">h:250</text>
     
   
    
     <!-- tekst strych -->      
      <text x="455" y="195">h:~20x2</text>
      <text x="425" y="445">h:~20</text>
      <text x="425" y="745">h:~20</text>
   
    
</svg>     
</section>

<?php $this->ob(); ?>
<script src="/js/mig/mig.canvas.view.js"></script>
    <script type="text/javascript">
    // <![CDATA[
  
   mig.canvas.view(window, {
            
        });
    // ]]>
    </script>
    <?php $this->clean(); ?>
    