<section> 
    <?php $this->render('projection/view/partial/tools.phtml'); ?>
   <!-- <div class="list-switcher">
     <a href="#" class="switcher" data-id-to-switch="lukarna-zachod">pokaż lukarna zachod</a>
     <a href="#" class="switcher" data-id-to-switch="lukarna-srodkowa">pokaż lukarna srodkowa</a>
     <a href="#" class="switcher" data-id-to-switch="lukarna-wschod">pokaż lukarna wschod</a>
    </div>-->
   <svg  version="1.1"
         baseProfile="full"
         accesskey=""
        class="svg-canvas"
         viewBox="0 0 1320 958"
         width="1320" 
         height="958">
   
<?php $this->render('projection/view/partial/style.phtml'); ?>
  
  <rect  x="0" y="0" width="1320" height="958" fill="#ccc" stroke="black"/>
  
  <rect  x="0" y="0" width="1320" height="428" fill="#99ccff" stroke="black"/> 
 
   <rect  x="42" y="748" width="888" height="210" fill="#fff" stroke="black"/> 
   <rect  x="972" y="748" width="310" height="210" fill="grey" stroke="black"/> 
  
   <rect  x="42" y="448" width="1236" height="280" fill="#fff" stroke="black"/>
   
     <!-- piwnica okna -->   
    
    <rect  x="199" y="780" width="100" height="71" fill="#ffccff" stroke="black"/>
   <rect  x="643" y="780" width="102" height="71" fill="#ffccff" stroke="black"/>
   
   <!-- kominy -->
   
   <rect  x="931" y="0" width="30" height="50" fill="#666" stroke="black"/>
   <rect  x="475" y="0" width="30" height="50" fill="#666" stroke="black"/>

    <!-- scianki -->
    
    <line x1="447" y1="448" x2="447" y2="728" stroke-width="1" stroke="black"/>
    <line x1="475" y1="448" x2="475" y2="728" stroke-width="1" stroke="black"/>
    
    <line x1="447" y1="748" x2="447" y2="958" stroke-width="1" stroke="black"/>
    <line x1="475" y1="748" x2="475" y2="958" stroke-width="1" stroke="black"/>
    
    <line x1="931" y1="448" x2="931" y2="728" stroke-width="1" stroke="black"/>
    <line x1="973" y1="448" x2="973" y2="728" stroke-width="1" stroke="black"/>
     
     <!--okna parter -->
     
    <rect  x="178" y="488" width="165" height="160" fill="#ffccff" stroke="black"/>    
    <rect  x="639" y="488" width="162" height="160" fill="#ffccff" stroke="black"/>     
    <rect  x="639" y="488" width="162" height="160" fill="transparent" stroke="black"/>
    
    <!-- grunt  -->
   <polygon points="0,908 0,958 1320,958 1320,863" fill="brown" stroke="black"/>
    
    <!-- teksty zachod--> 
    <text x="185" y="593">h:162,w:160</text>
   <text x="185" y="833">h:71,w:100</text>
    
     <!-- tekst srodek --> 
   <text x="650" y="593">h:160x160</text>
    <text x="650" y="833">h:71,w:102</text> 
     <text x="60" y="340">h:428 strych</text>
     <text x="60" y="680">h:280 parter</text>
     <text x="60" y="880">h:210 piwnica</text>
         
     <!-- tekst stropy -->
      <text x="425" y="445">h:~20 strop drewniany</text>
      <text x="425" y="745">h:~20 strop Kleina</text>
   
    
</svg>     
</section>

<?php $this->ob(); ?>
<script src="/js/mig/mig.canvas.view.js"></script>
    <script type="text/javascript">
    // <![CDATA[
    // 
    // 
        //var canv = jQuery('#canvas');
   
   //console.log(canv);
   //
   mig.canvas.view(window, {
            
        });
    // ]]>
    </script>
    <?php $this->clean(); ?>
    